### ISSUE TITLE
在编译disconf-web时候报错

### ISSUE THREAD

**Issue by dnfhujun** [knightliao/disconf#105]
按照教程里安装disconf-web

mkdir /home/disconf/online-resources  
mkdir /home/disconf/war  
cd disconf-master  
mvn clean install  
ONLINE_CONFIG_PATH=/home/disconf/online-resources  
WAR_ROOT_PATH=/home/disconf/war  
export ONLINE_CONFIG_PATH  
export WAR_ROOT_PATH  
cd disconf-web  
sh deploy/deploy.sh  

在执行 mvn clean install 的时候，报错了，如下：
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.1:compile (default-compile) on project disconf-core: Compilation failure: Compilation failure:
[ERROR] /home/hujun/disconf-master/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/retry/impl/RetryStrategyRoundBin.java:[31,42] 无法确定 <T>T 的类型参数；对于上限为 T,java.lang.Object 的类型变量 T，不存在唯一最大实例
[ERROR] /home/hujun/disconf-master/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/impl/RestfulMgrImpl.java:[61,41] 无法确定 <T>T 的类型参数；对于上限为 T,java.lang.Object 的类型变量 T，不存在唯一最大实例

**Comment by knightliao** [comment]
http://www.cnblogs.com/peida/p/4218210.html

可能是java sdk包版本有问题，升级一下试试

**Comment by dnfhujun** [comment]
非常感谢，确实是jdk的问题，升级到1.7就ok了！
