### ISSUE TITLE
登录后又被踢出

### ISSUE THREAD

**Issue by xiongchen2012** [knightliao/disconf#115]
按照WEB部署文档部署好以后：

进入登录页面，登录后主页面一闪而过，然后又被踢出到登录页面；

后台日志如下：
`14:36:57.860 [http-nio-8080-exec-5] INFO  c.b.d.c.i.login.LoginInterceptor - /disconf/api/account/signin
14:36:57.865 [http-nio-8080-exec-5] INFO  c.b.d.web.web.auth.UserController - com.baidu.disconf.web.service.sign.form.SigninForm@79f61d67
14:36:57.866 [http-nio-8080-exec-5] DEBUG com.baidu.dsp.common.dao.AbstractDao - ----null	disconf.user
14:36:57.866 [http-nio-8080-exec-5] DEBUG com.baidu.dsp.common.dao.AbstractDao - select password,role_id,user_id,name,ownapps,token from disconf.user where name=? limit ?, ?	[admin, 0, 1]
14:36:57.866 [http-nio-8080-exec-5] DEBUG c.b.u.c.d.d.VirtualDataSource - use random datasource.
14:36:57.870 [http-nio-8080-exec-5] DEBUG c.b.u.c.d.d.VirtualDataSource - use random datasource.
14:36:57.871 [http-nio-8080-exec-5] DEBUG com.baidu.dsp.common.dao.AbstractDao - ----null	disconf.user
14:36:57.871 [http-nio-8080-exec-5] DEBUG com.baidu.dsp.common.dao.AbstractDao - select password,role_id,user_id,name,ownapps,token from disconf.user where name=? limit ?, ?	[admin, 0, 1]
14:36:57.872 [http-nio-8080-exec-5] DEBUG com.baidu.dsp.common.dao.AbstractDao - ----null	disconf.user
14:36:57.877 [http-nio-8080-exec-5] INFO  c.b.dsp.common.vo.JsonObjectUtils - JsonObject(result={visitor=VisitorVo [id=6, name=admin, role=null]})
14:36:58.309 [http-nio-8080-exec-6] INFO  c.b.d.c.i.login.LoginInterceptor - /disconf/api/account/session
14:36:58.312 [http-nio-8080-exec-6] INFO  c.b.dsp.common.vo.JsonObjectUtils - JsonObjectBase [message={global=请登录系统}, sessionId=b7b1ee72-769c-49f8-b82d-4b8400b8b7ff, success=false]
14:36:58.312 [http-nio-8080-exec-4] INFO  c.b.d.c.i.login.LoginInterceptor - /disconf/api/env/list
14:36:58.311 [http-nio-8080-exec-7] INFO  c.b.d.c.i.login.LoginInterceptor - /disconf/api/app/list
14:36:58.313 [http-nio-8080-exec-4] INFO  c.b.dsp.common.vo.JsonObjectUtils - JsonObjectBase [message={global=请登录系统}, sessionId=9bb39513-33f7-4607-aa42-3be469584580, success=false]
14:36:58.313 [http-nio-8080-exec-7] INFO  c.b.dsp.common.vo.JsonObjectUtils - JsonObjectBase [message={global=请登录系统}, sessionId=ddefdef1-3de0-4479-a918-5ae3e7f991a8, success=false]
14:36:58.737 [http-nio-8080-exec-8] INFO  c.b.d.c.i.login.LoginInterceptor - /disconf/api/account/session
14:36:58.738 [http-nio-8080-exec-8] INFO  c.b.dsp.common.vo.JsonObjectUtils - JsonObjectBase [message={global=请登录系统}, sessionId=7b757eaf-96a7-4fa2-8e9f-fefe18f1b41f, success=false]
`

**Comment by knightliao** [comment]
需要设置一下 domain （比如你的域名是 a.baidu.com） 否则session无法保存

**Comment by xiongchen2012** [comment]
我后来试了下，必须是配置在tomcat根目录，也就是/下才可以。二级目录会发生这个问题。我明天试一下domain，多谢回答。

**Comment by knightliao** [comment]
http://disconf.readthedocs.io/zh_CN/stable/install/src/02.html
