### ISSUE TITLE
log配置文件

### ISSUE THREAD

**Issue by damingzms** [knightliao/disconf#116]
log配置文件，比如log4j，如果放到disconf服务器来维护，客户端系统第一次启动好像会提示找不到log4j配置，应该是因为log4j配置文件不由spring管理，而且在disconf下载配置文件之前log4j就已经需要读取配置文件了。
有没有什么办法？

**Comment by knightliao** [comment]
可以尝试在你的启动脚本加入以加代码，然后在 平台上 上传 log4j.properties 

        #
	# wget log4j
	#
	arr=${JAVA_OPTS}
	for key in ${arr}
	do
		x="$(echo ${key} | awk -F '=' '{ print $1 "=" $2}')"
		for i in ${x};
		do
			if [[ ${i} == *"Ddisconf"* ]] ;then
				if [[ ${i} == *"Ddisconf.conf_server"* ]] ;then
					disconf_server=`echo $i | awk -F '=' '{print $2}'`
				fi
				if [[ ${i} == *"Ddisconf.app"* ]] ;then
					disconf_app=`echo $i | awk -F '=' '{print $2}'`
				fi
				if [[ ${i} == *"Ddisconf.version"* ]] ;then
					disconf_version=`echo $i | awk -F '=' '{print $2}'`
				fi
				if [[ ${i} == *"Ddisconf.env"* ]] ;then
					disconf_env=`echo $i | awk -F '=' '{print $2}'`
				fi
			fi
		done
	done

**Comment by kazaff** [comment]
没看懂这个脚本啥意思？能否解释一下呢？

**Comment by knightliao** [comment]
就是程序启动前 使用shell+ 环境变量 去配置中心获取 log4j.properties
