### ISSUE TITLE
为啥只有4套环境？

### ISSUE THREAD

**Issue by jingxiaoyang1988** [knightliao/disconf#117]
目前是不是只有4套环境 rd,qa,local,online 4套环境 ，能不能自由添加环境

**Comment by knightliao** [comment]
目前还没有环境的扩展web接口，你可以通过version来进行扩充，例如   qa环境下可以有 test1 test2 test3 ..

**Comment by xiongchen2012** [comment]
对哦，这4个不同公司名字不一样。能否自定义呢？比如online我们公司一般叫production

**Comment by damingzms** [comment]
我这边直接修改数据库

**Comment by Smilence1024** [comment]
可以直接修改数据库，自己定义环境名称吧
