### ISSUE TITLE
可不可以自动忽略某些不存在的配置文件？

### ISSUE THREAD

**Issue by damingzms** [knightliao/disconf#119]
为了客户端项目和disconf的解耦，我另外写了个jar来封装disconf-client，jar包里面定义了很多config类，然后打算让不同的项目直接引用，但是因为各个项目的配置文件不同，jar包里面定义的配置类是所有项目的配置文件合集。
   这样就有个问题，因为单个项目对应的app上面的配置文件只是jar包里面定义的配置类的子集，这样缺少的配置文件就会报错
   有没有什么设置可以自动忽略这些不存在的配置文件，只是log的形式列出使用的配置文件就好？

**Comment by knightliao** [comment]
你是使用注解式的，还是XML式的？

**Comment by damingzms** [comment]
注解式

**Comment by caokaifang** [comment]
麻烦问下现在的disconf版本支持忽略不存在的配置文件吗？

**Comment by knightliao** [comment]
@caokaifang 可以支持，disconf.ignore配置一下

**Comment by knightliao** [comment]
每个项目启动时 动态参数设置一下 disconf.ignore 试下
