### ISSUE TITLE
zoo.properties

### ISSUE THREAD

**Issue by javaperson** [knightliao/disconf#12]
zoo.properties 里面的两个属性什么意思，应该如何配置。
zookeeper如何配置启动，能给个例子吗？

**Comment by knightliao** [comment]
hi
hosts 是指 ZK集群的地址，你应该关心这个配置，需要更改这个配置
zookeeper_url_prefix  是ZK的前缀使用，一般来说，你不用关心这个属性，不需要更改

**Comment by javaperson** [comment]
我想知道怎么搭建zk集群，能给个配置的例子么。

**Comment by knightliao** [comment]
建议看下 http://zookeeper.apache.org/doc/trunk/zookeeperStarted.html
