### ISSUE TITLE
是我太菜还是文档太糙？

### ISSUE THREAD

**Issue by kazaff** [knightliao/disconf#120]
感激开源了好东西，同时也对文档有些失望了~
我不是喷子，只是拿文档和其它开源项目比，真是忍不住吐槽啊~

**Comment by sulinixl** [comment]
文档确实非常粗糙

**Comment by imsandy** [comment]
文档是糙

**Comment by hmilylife** [comment]
槽。。

**Comment by justciffer** [comment]
设计文档和使用文档混在一起真的好么

**Comment by knightliao** [comment]
文档放到 http://disconf.readthedocs.io/zh_CN/latest/index.html 上了
会继续改进
