### ISSUE TITLE
自定义 disconf.properties 文件的路径在哪设置？

### ISSUE THREAD

**Issue by Smilence1024** [knightliao/disconf#121]
-Ddisconf.conf=/tmp/disconf.properties

这是设置添加到哪里？这个路径是绝对路径吗？

**Comment by knightliao** [comment]
可以是绝对路径  也可以相对路径 。如果是命令行 则是 和你当前路径的相对路径 ；如果是tomcat则是相对于classpath的

**Comment by Smilence1024** [comment]
好哒，谢谢
