### ISSUE TITLE
咨询？何时可以支撑非JAVA语言客户端

### ISSUE THREAD

**Issue by mircoteam** [knightliao/disconf#123]
咨询？何时可以支撑非JAVA语言客户端

**Comment by kazaff** [comment]
同关注

**Comment by Corey600** [comment]
自己码了个node的客户端，基本功能都以实现，测试还未完善，求轻拍。。。。
https://github.com/Corey600/node-disconf-client

**Comment by knightliao** [comment]
@Corey600 不错啊，我瞅瞅，回头帮你做推荐

**Comment by Corey600** [comment]
@knightliao 谢谢哈，希望有更多的人的指导和建议 :)

**Comment by knightliao** [comment]
http://disconf.readthedocs.io/zh_CN/dev/others/src/contribute.html
