### ISSUE TITLE
bug:配置的user_define_download_dir并没有生效

### ISSUE THREAD

**Issue by friddle** [knightliao/disconf#124]
系统参数加了：-Ddisconf.user_define_download_dir=/tmp/disconf

经过系统的Debug，配置的读取设置都没有问题。
下载文件夹地址(下行代码的localFileDirTemp)指向的是DisClientSysConfig中的LOCAL_DOWNLOAD_DIR变量而不是DisClientConfig中的 userDefineDownloadDir变量(而localFileDir是指向这个目录的)。而上一个变量是不可设置的。

建议是RestfulMgrImpl的downloadFromServer函数的调用这一行
```java
File tmpFilePathUniqueFile = retryDownload(localFileDirTemp, fileName, remoteUrl, retryTimes,
                    retrySleepSeconds);
```
改成

```java    
File tmpFilePathUniqueFile = retryDownload(localFileDir, fileName, remoteUrl, retryTimes,
                    retrySleepSeconds);
```

你的注释也是这个意思。现在到这个用户定义的目录。但是并没有用到用户定义的目录。

否则我一直都报权限错误。修改了这个配置没有任何作用。
希望下个版本就能解决。

**Comment by friddle** [comment]
触发理由是

   <bean id="remote_reload_configuration"
          class="com.baidu.disconf.client.addons.properties.ReloadablePropertiesFactoryBean">
        <property name="locations">
            <list>
                <value>conf/test.properties</value>
            </list>
        </property>
    </bean>

`conf/test.properties`没有加classpath才触发了这个权限问题。

**Comment by knightliao** [comment]
这个问题解决了没有？

**Comment by friddle** [comment]
这个问题是自定义下载地址不生效。后来是发现没必要自定义下载地址了。
