### ISSUE TITLE
提供的spring-boot-demo中为何找不到zk的配置文件

### ISSUE THREAD

**Issue by kazaff** [knightliao/disconf#125]
其他两种demo也同样如此，根据架构图disconf-client不是一样要和zk通信么？那为何demo中只看到了disconf-web的配置，而没有zk的配置呢？

**Comment by kazaff** [comment]
难道该配置信息是也是从disconf-web的接口中获取得到的？

**Comment by knightliao** [comment]
是的，zk的地址是从 disconf-web获取的

**Comment by kazaff** [comment]
@knightliao 谢谢确认~
