### ISSUE TITLE
disconf-web 2.6.35版本中的readme.md描述缺20160701.sql

### ISSUE THREAD

**Issue by xiaolianghu** [knightliao/disconf#128]
disconf-web 的最新代码2.6.35中按照document部署发现保存配置文件或配置项报错了，最后通过跑源码发现是20160701.sql这段数据库脚本没有执行。
希望将20160701.sql添加到readme.md并更新document。
新注册的github用户，正在准备使用disconf，谢谢！

**Comment by knightliao** [comment]
已经添加，谢谢提醒
