### ISSUE TITLE
请问你接受pull request吗? 有几个单元测试的小改动希望采纳

### ISSUE THREAD

**Issue by Calabor-Hoc** [knightliao/disconf#13]
在单元测试中, 你使用了wiremock建了个假服务器, 但是这个URL匹配是很死板的, 比如url`/api/config/file?app=disconf_testcase&env=rd&type=0&key=confA.properties&version=1_0_0_0`, 有时候你的测试用例中发注的请求url跟上面不一样, 往往是query parameter的顺序不一样, 比如key=key在version=version的后面, 因此url导致不匹配, 假服务器不反回期望的请求.  
```java
stubFor(get(urlEqualTo(RemoteMockServer.ITEM_URL))
                    .willReturn(aResponse().withHeader("Content-Type", RemoteMockServer.CONTENT_TYPE).withStatus(200)
                                    .withBody(GsonUtils.toJson(valueVo))));
```

长话短说, query parameter顺序不一样是因为遍历HashMap的顺序是随机的, 可能在你的环境中恰好这些单元测试都跑过了, 另一种环境就不行了. 我这里的症状是, 在Eclipse的JUnit跑没问题, mvn test 就不行了.

如果接受pull request的话, 我可以做些改动, 尽量减少源代码的改动的情况下解决这个单测的问题. 要动的地方只有`RemoteMockServer.java`和`BaseCoreTestCase.java`这两个类

**Comment by knightliao** [comment]
抱歉，现在才看到，你可以进行改动，你发个pull request过来：）
