### ISSUE TITLE
完全自定义配置文件的解析流程，而不用默认的配置类字段自动注入？？？

### ISSUE THREAD

**Issue by xiaolianghu** [knightliao/disconf#130]
现在的配置文件（比如simple.properties）会映射到对应的配置类，比如SimpleConfig。
disconf-client会下载simple.properties到本地，并实现配置类字段的自动注入。

但是是否能够让使用者能够按照业务需求自己解析配置文件，而不用采用默认的配置类字段自动注入？

在有些场景中，配置文件里面的配置信息是不能完全确定的，比如：
database1.url=192.168.1.11
database2.url=192.168.1.12
database3.url=192.168.1.13
database4.url=192.168.1.14
。。。。。

这样的话，配置类在编译阶段是无法确定字段的个数！

**Comment by knightliao** [comment]
对于动态的，你可以使用 https://github.com/knightliao/disconf/wiki/2.6.34

**Comment by xiangzhiwei** [comment]
如果使用动态的DisconfDataGetter.getByFile("redis.properties"),必须配合@DisconfFileItem,否则读到的就是null。可否不使用注解，直接使用这种方法呢
