### ISSUE TITLE
2.6.35版本会换行，2.6.34不会

### ISSUE THREAD

**Issue by imsandy** [knightliao/disconf#133]
2.6.35 文件下下来如果有注释，会全部变成一行。导致读取不到配置，求大神帮忙
#0\\uff1a\\u5f00\\u53d1\\uff0c1\\uff1a\\u6d4b\\u8bd5\\uff0c2\\uff1a\\u6b63\\u5f0f \r\ndb.type=0\r\n\r\n#

**Comment by imsandy** [comment]
有没有注释都会合并到同一行。。。。。

**Comment by knightliao** [comment]
hi, sorry, 2.6.35发布时出了些小问题，

https://github.com/knightliao/disconf/releases/tag/2.6.35-2 你下载这里的，或者获取最新的master的 可以解决你的问题

**Comment by imsandy** [comment]
谢谢大神，问题解决了
