### ISSUE TITLE
xml类型的配置文件还不支持？

### ISSUE THREAD

**Issue by Smilence1024** [knightliao/disconf#136]
我看到DisconfXmlProcessorImpl里面对xml类型的文件还没有做处理，这个什么时候能完成?
现在只支持properties类型的配置文件吗？

**Comment by knightliao** [comment]
目前还没有支持，未来会采用 用户自定义解析方法 的方式提供

**Comment by xiaotutiger** [comment]
嗯 和xstram结合在一起直接返回解析类会比较给力
