### ISSUE TITLE
主干代码disconf-web 现在构建后编译报错

### ISSUE THREAD

**Issue by huotaihe** [knightliao/disconf#138]
com.baidu.disconf.web.service.app.bo.App类缺少getApp()、getDesc()、getEmails()方法；
com.baidu.disconf.web.service.config.bo.Config类缺少getValue()方法；
还有其他的后面再补充！

**Comment by caoyaochong** [comment]
遇到同样的问题，
master分支 ，disconf-web 模块，
编译后出现大量问题，都是缺少类中方法引起：
The method getApp() is undefined for the type AppNewForm
The method getAppId() is undefined for the type Config
The method getAppId() is undefined for the type ConfListForm
The method getCreateTime() is undefined for the type Config
The method getDesc() is undefined for the type AppNewForm
The method getEmails() is undefined for the type AppNewForm
The method getEnvId() is undefined for the type Config
The method getEnvId() is undefined for the type ConfListForm
The method getName() is undefined for the type Config
....
等等 这里没有一一列举

**Comment by knightliao** [comment]
https://github.com/knightliao/disconf/issues/38

**Comment by guangqan** [comment]
自己手动加了get set
