### ISSUE TITLE
版本2.6.22和2.6.23配置文件更新后回调方法没触发

### ISSUE THREAD

**Issue by 269941633** [knightliao/disconf#14]
第一次使用disconf，看了官方文档后，下载版本2.6.23研究，发现web端更改配置后，client端的自己做的例子的回调方法就是无法触发，然后下载了2.6.21，client端的回调方法就正常触发了.然后看到版本2.6.22说修复了个bug，所以我又下载了版本2.6.22，测试时发现client端的回调方法又不触发了。就2.6.21正常。。。对2.6.23代码稍微跟踪了下，web更改配置后，client端里的DisconfCoreProcessUtils类callOneConf方法里的List<IDisconfUpdate> iDisconfUpdates = disconfStoreProcessor.getUpdateCallbackList(key)时，是空的，所以回调类里的reload没触发。但是2.6.21却可以正常。。。;请问，这是怎么回事，是不是版本2.6.22修复bug或删除多余代码引起的，导致IDisconfUpdate的实现类没被扫描到啊？

**Comment by knightliao** [comment]
稍等，我今天看下

**Comment by knightliao** [comment]
hi, 确实是bug啊， https://github.com/knightliao/disconf/issues/11

当时我没重视，现在已经修复了 在 2.6.24 非常感谢~！
