### ISSUE TITLE
编程式获取配置

### ISSUE THREAD

**Issue by imsandy** [knightliao/disconf#142]
如何用java代码获取配置DisconfStoreProcessor disconfStoreProcessor = DisconfStoreProcessorFactory.getDisconfStoreFileProcessor();，在设置disconf.enable.remote.conf=false时，拿不到配置，我需要有个地方可以直接拿到配置，能否支持

**Comment by knightliao** [comment]
可以使用 https://github.com/knightliao/disconf/wiki/2.6.34  这里的方式 进行获取数据
