### ISSUE TITLE
disconf, client怎么使用主备?

### ISSUE THREAD

**Issue by caoyaochong** [knightliao/disconf#144]
Hi ， @knightliao 
  阅读wiki文档的时候，对 “怎么设置异构系统的多个实例， 特别是异构系统主备之间的切换？ 以及 Context的切换” 有一些疑问。
  作者在文档中有提及，但是没有具有讲述client端的使用方式、

 希望百忙之中能补充一下文档，万分感谢。  : )

**Comment by guangqan** [comment]
同问

**Comment by knightliao** [comment]
disconf-client本来还想支持 主备竞争 以及 主备自动切换时自动切换配置 的功能，但后来觉得 功能可能不是特别强需求，没有进行开发
