### ISSUE TITLE
配置文件修改 修改方式：输入文本   汉字会出现乱码的情况

### ISSUE THREAD

**Issue by xiaolianghu** [knightliao/disconf#145]
如题！

![image](https://cloud.githubusercontent.com/assets/20347953/17209916/3f27478c-54f2-11e6-8aa7-b41f40c08779.png)

**Comment by knightliao** [comment]
![image](https://cloud.githubusercontent.com/assets/3657476/17512185/42a1e302-5e59-11e6-99e5-0a8115d6ac04.png)

会不会是浏览器编码的问题？我这边都是ok的

**Comment by junzi2099** [comment]
我也遇到类似的问题，追查发现是mysql数据库编码非utf8导致，所以建议看看数据表里是不是也存的乱码，如果是，把数据库改成utf8就能解决。
