### ISSUE TITLE
@DisconfFile @DisconfItem能否放开配置app?

### ISSUE THREAD

**Issue by islife** [knightliao/disconf#147]
既然@DisconfFile @DisconfItem都能配置env和version，能否再放开配置app，实现将部分共享配置作为一个share app？

**Comment by moluqianli** [comment]
自己改源码好了

**Comment by knightliao** [comment]
sorry, 最近公司事务比较忙，下个版本将会开放，

**Comment by islife** [comment]
@moluqianli 自己已经改过了，只是觉得可以作为一个点加进来

**Comment by knightliao** [comment]
fix http://disconf.readthedocs.io/zh_CN/latest/others/src/update.html

**Comment by wzheart** [comment]
具体该如何配置呢？毕竟client只能引用一个app的版本啊。

**Comment by wzheart** [comment]
在client中源码中了解到了，原来这个share还只是在同一个app中进行版本划分，然后再到client中引用。
我以为是不同的app有这父子级别关系，类似maven的结构。

**Comment by nickle-ye** [comment]
@wzheart , 我想这个原因是为什么当初 @knightliao 不放开app的原因吧~~

**Comment by songwie** [comment]
请问  多个app共享一个配置的解决了么
