### ISSUE TITLE
请问怎么保证qa,local,online上的配置项一致？

### ISSUE THREAD

**Issue by CliffYuan** [knightliao/disconf#155]
![qq 20160820001806](https://cloud.githubusercontent.com/assets/1629229/17816423/9f123302-666b-11e6-8156-56679bfaac73.png)
![qq 20160820001813](https://cloud.githubusercontent.com/assets/1629229/17816424/9f96469c-666b-11e6-982e-e057a0e06174.png)

同一个项目，同一个版本，不同环境，配置项目可以不一样呢？
谢谢

**Comment by knightliao** [comment]
目前并没有做严格的限制
