### ISSUE TITLE
disconf不支持https

### ISSUE THREAD

**Issue by guangqan** [knightliao/disconf#158]
在com.baidu.disconf.core.common.restful.core.RemoteUrl.RemoteUrl(String, List<String>)里面，以下代码
                if (!server.contains("http://")) {
                    server = "http://" + server;
                }
写死了，配置如果没有http://，那么会自动加上。但如果disconf-web是https，则无论如何都支持不了。

**Comment by knightliao** [comment]
这个确实，我来fix

**Comment by knightliao** [comment]
fix http://disconf.readthedocs.io/zh_CN/latest/others/src/update.html
