### ISSUE TITLE
sh deploy/deploy.sh 报错

### ISSUE THREAD

**Issue by ztd770960436** [knightliao/disconf#164]
**********************************************
copy online config  /home/disconf/online-resources
**********************************************
cp: cannot stat `/home/disconf/online-resources/*': No such file or directory

**Comment by knightliao** [comment]
需要设置一下以下路径 
ONLINE_CONFIG_PATH=/home/work/dsp/disconf-rd/online-resources
WAR_ROOT_PATH=/home/work/dsp/disconf-rd/war
export ONLINE_CONFIG_PATH
export WAR_ROOT_PATH

http://disconf.readthedocs.io/zh_CN/latest/install/src/02.html
