### ISSUE TITLE
disconf-web一访问就种植cookie，还是登录的时候种植cookie，我测试的时候没有发现种植cookie，如图所示

### ISSUE THREAD

**Issue by lyg123** [knightliao/disconf#170]

**Comment by lyg123** [comment]
![image](https://cloud.githubusercontent.com/assets/17899660/18382962/d98cbad4-76b5-11e6-9786-d0c7d4339bf0.png)

**Comment by xiangzhiwei** [comment]
redis 必须配置密码

**Comment by knightliao** [comment]
![image](https://cloud.githubusercontent.com/assets/3657476/18409857/d405df12-7784-11e6-993d-1df3fafc4914.png)

访问域名是否设置正确？

**Comment by lyg123** [comment]
@knightliao 域名设置正确了，一样的都是localhost，调试代码发现走了种植cookie方法
![image](https://cloud.githubusercontent.com/assets/17899660/18422368/9a260dd2-78cc-11e6-896f-0aed631f881f.png)
，但是cookie浏览器没有，
@xiangzhiwei种植cookie跟redis设置密码有关系嘛，哪里代码看到此关系了

**Comment by lyg123** [comment]
@knightliao 
![image](https://cloud.githubusercontent.com/assets/17899660/18422384/daf2c030-78cc-11e6-8461-63b8f743afd1.png)

**Comment by knightliao** [comment]
你试下别的域名 例如 disconf.com 之类的

**Comment by lyg123** [comment]
换成disconf.com就有cookie了，请指点下，发生了什么？

**Comment by knightliao** [comment]
localhost指定不了

**Comment by lyg123** [comment]
这是cookie的本身的机制吗

**Comment by knightliao** [comment]
https://www.sov5.com/search?q=cookie+localhost&re=1 看第一条答案

**Comment by lyg123** [comment]
谢谢
