### ISSUE TITLE
我新部署的为啥登陆不了呢？

### ISSUE THREAD

**Issue by yangxq007** [knightliao/disconf#172]
admin/admin  登陆的时候浏览器报路径404 啥原因？

jquery-1.11.0.js:9666 POST http://192.168.1.201:8081/api/account/signin 404 (Not Found)

**Comment by knightliao** [comment]
http://disconf.readthedocs.io/zh_CN/stable/install/src/02.html  你再看看这个

**Comment by yangxq007** [comment]
我是按照安装文档一步步操作的，但是tomcat启动后,登陆就报错了，正不知道哪里出错了？第一次用这个还请指教啊！

**Comment by frank266** [comment]
我也碰到了这个问题，启动日志显示正常，就是访问不了，404

**Comment by knightliao** [comment]
@frank266 还是没有启动成功
