### ISSUE TITLE
页面样式问题

### ISSUE THREAD

**Issue by yangxq007** [knightliao/disconf#175]
样式表单 http://192.168.31.201:8081/dep/bootstrap/css/bootstrap.css 未载入，因为它的 MIME 类型 "text/html" 不是 "text/css"。main.html
样式表单 http://192.168.31.201:8081/dep/bootstrap/css/noie.css 未载入，因为它的 MIME 类型 "text/plain" 不是 "text/css"。main.html
样式表单 http://192.168.31.201:8081/dep/jquery-ui-1.10.4.custom/css/ui-lightness/jquery-ui-1.10.4.custom.css 未载入，因为它的 MIME 类型 "text/plain" 不是 "text/css"。main.html
样式表单 http://192.168.31.201:8081/assets/css/project.css 未载入，因为它的 MIME 类型 "text/plain" 不是 "text/css"。

导致css样式无法加载，请问是啥原因，请大神解惑！

**Comment by knightliao** [comment]
应该是nginx的static page没设置好
