### ISSUE TITLE
多个client 需要怎么配置

### ISSUE THREAD

**Issue by ykdsg** [knightliao/disconf#182]
比如系统A在他提供的client中依赖了disconf 的配置，设置了package com.a.***，系统B 依赖了系统A的client ，同时系统B本身使用了配置了disconf，设置了package com.b.***，这样是否会有问题？

**Comment by knightliao** [comment]
那系统B 应该 要在配置里 包含了 系统A的client的配置

**Comment by ykdsg** [comment]
disconf 中的是2个不同的app，比如系统A是appA，系统b是appB ，这样系统B在配置的时候需要怎么设置
