### ISSUE TITLE
Property 'uploadTempDir' threw exception;

### ISSUE THREAD

**Issue by verlen** [knightliao/disconf#188]
我在ubuntu14.04为基础的docker下配置disconf，打好war包启动tomcat时失败，报下面这个错误。
跟数据库有关吗，其他配置都做好了，sql文件夹下没有文件的说。

`2016-10-08 10:11:16,510 [localhost-startStop-1] WARN  support.XmlWebApplicationContext (AbstractApplicationContext.java:487)     - Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'multipartResolver' defined in URL [file:/root/resource/disconf/share/war/WEB-INF/classes/spring-servlet.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'uploadTempDir' threw exception; nested exception is java.lang.IllegalArgumentException: Given uploadTempDir [ServletContext resource [/tmp]] could not be created
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)`

**Comment by verlen** [comment]
这个500错误好像是随缘出现的，只要各种花样改配置就行了。
ps：真的快配疯了哎。。

**Comment by xiechao** [comment]
@cheny1ran 你好，能不能请教一下，你是怎么解决的吗，我也遇见了这个问题

**Comment by cheny1ran** [comment]
@xiechao 具体忘记了 你试下手建 /tmp 目录再改下目录权限,这个项目在 docker 里弄很多问题都是权限问题.

**Comment by xdjiangyang** [comment]
@xiechao @cheny1ran 我也遇到这个问题，我的解决方案是将 war 目录所属的组和用户改为 tomcat
