### ISSUE TITLE
同时使用context:property-placeholder 报错

### ISSUE THREAD

**Issue by ykdsg** [knightliao/disconf#190]
如果配置里面已经有context:property-placeholder，再使用基于xml分布式 配置的ReloadablePropertiesFactoryBean，就会报 Could not resolve placeholder

**Comment by ykdsg** [comment]
context:property-placeholder 需要配置ignore-unresolvable="true"，这样就可以了

**Comment by markyao** [comment]
1，<context:property-placeholder/>命名空间的配置内部就是创建一个PropertySourcesPlaceholderConfigurer bean 。
2，context:property-placeholder配置先基于xml 配置的ReloadablePropertiesFactoryBean，bean扫描时先扫描命名空间配置的bean, 此时配置文件还没有下载下来，自然出现问题。
3，如果基于ReloadablePropertiesFactoryBean配置的文件和<context:property-placeholder/>指向的是同一个配置文件，那么基于<context:property-placeholder/>配置可以不需要再使用，因为按照disconf配置，它们两者使用功能一致的。
