### ISSUE TITLE
关于设计

### ISSUE THREAD

**Issue by gaoxianglong** [knightliao/disconf#191]
http://www.oschina.net/p/disconf
关于细节设计的连接进不去。

为何部署disconf需要部署那么多的外围系统依赖？
disconf集群，使用nginx做负载？
disconf用户管理，用mysql？
disconf配置信息及watch，用zookeeper？
redis呢？Mysql Master/Slave不可用时，redis顶？实现HA？

**Comment by knightliao** [comment]
http://disconf.readthedocs.io/zh_CN/latest/ 这里有
