### ISSUE TITLE
使用文件托管，自动reload方式，每次修改都会自动热部署吗

### ISSUE THREAD

**Issue by frank266** [knightliao/disconf#192]
发现只要修改了配置，就像自动重启一次

**Comment by frank266** [comment]
检测到classpath有变动，tomcat就会自动reload，所以在设置configproperties_disconf中的location的时候，将路径设置成某个绝对路径，就可以了

**Comment by HelloBiao** [comment]
这个具体应该怎么操作啊？我的好像也是，会自动加载配置文件，托管不是不加载的吗
