### ISSUE TITLE
修改disconf.user_define_download_dir为自定义路径并没有生效

### ISSUE THREAD

**Issue by fooololo** [knightliao/disconf#193]
我把disconf.user_define_download_dir修改成一个自定义目录，但是应用启动时还是向./disconf/download下载

另外在tomcat启动时，下载的路径是tomcat/bin/./disconf/download,这是什么情况？

配置：
disconf.user_define_download_dir=/tmp/disconf/aaa
disconf.enable_local_download_dir_in_class_path=true

错误：
TO: /data/tomcat_api/bin/./disconf/download

**Comment by fooololo** [comment]
配置：
disconf.user_define_download_dir=/tmp/disconf/aaa
disconf.enable_local_download_dir_in_class_path=true

错误：
 TO: /data/tomcat_api/bin/./disconf/download

**Comment by frank266** [comment]
跟一下源码吧，我修改的就可以，配置如下
enable_local_download_dir_in_class_path=false;
user_define_download_dir=D:\\aaa\\vvv
上一条设置成false是因为应用检测到classpath下有文件变动，就会reload，相当于重启了应用

你的情况可以检查一下你设置的目录是否有权限

**Comment by fooololo** [comment]
@frank266 
是的，我解决了，我把源码里的disconf_sys.properties文件在我的应用里也放了一份，覆盖了disconf.local_download_dir
关键就是默认的disconf.local_download_dir是个相对路径，不一定有写权限，建议 @knightliao 优化这个配置

**Comment by knightliao** [comment]
@fooololo ok
