### ISSUE TITLE
disconf-web是否支持集群配置

### ISSUE THREAD

**Issue by paul527** [knightliao/disconf#195]
因为zookeeper只起到实时通知的作用，配置内容是从disconf-web获取，所以disconf-web的稳定性就很重要，我没有看到集群配置，能否给个参考例子，谢谢。

**Comment by fooololo** [comment]
可以的，nginx后面加多个disconf-web就行了

在应用里disconf.conf_server_host配置多个ip:port即可

**Comment by paul527** [comment]
起多个disconf-web，配置文件会自动同步吗？

**Comment by lijianqiang** [comment]
disconf-web 可以起多个啊，nginx里配一个专门做admin管理的，操作html页面的。然后起多个disconf-web，作api服务， 记住这个机器的ip，填到disconf.conf_server_host，专门给client调。
还可以做法是admin.sample.com配一台tomcat做管理。
api.sample.com配一台或多台机器起任意个tomcat实例，和admin端同用一个数据库，nginx里做负载均衡就好，disconf.conf_server_host配置域名就行了。
