### ISSUE TITLE
请教：某些情况下，会不会出现client收不到zookeeper的通知？

### ISSUE THREAD

**Issue by 54ebb** [knightliao/disconf#198]
在web上修改了某个配置的值，但是当时正好网络慢、或网络闪断、或应用正在重启过程中，会不会出现client收不到zookeeper的通知？貌似client也不知道自己是不是漏收了通知？
如果是小概率事件，你们是如何解决的？谢谢

**Comment by CrossChan** [comment]
代码显示一旦出现web的数据库和zoo中的值不一样，这里面用的是定时任务（半小时一次）检验，发现不同会发邮件

**Comment by knightliao** [comment]
hi, 如果网络不稳定, client与ZK失去连接，client会不断的进行重连，并有相应日志打印出来。一般来说，你可以 1）三台ZK保持稳定   2）监控日志是否有不断重连现象  
如果ZK与client发生断连，这样服务器的配置与client的配置就会发生不一致。 这时 web的监控系统就会发现。 并且有报警邮件。 这时 需要重新启动 客户端，以保持一致。
