### ISSUE TITLE
应用启动后disconf实例列表存在几秒钟自动消失

### ISSUE THREAD

**Issue by fooololo** [knightliao/disconf#200]
应用启动后与获取配置正常，但是几秒之后在disconf后台就看不到实例了
日志输出"******************************\* DISCONF CLOSE *******************************"

引起这个问题的代码我找到了：
![image](https://cloud.githubusercontent.com/assets/7138642/19477454/c23e21ea-9570-11e6-82ce-3b2863e604e2.png)
 即com.baidu.disconf.client.addons.properties.ReloadingPropertyPlaceholderConfigurer在启动后不久就销毁了
![image](https://cloud.githubusercontent.com/assets/7138642/19477502/fb063652-9570-11e6-9ee7-a07e670caf1e.png)

具体原因已找到，使用disconf静态配置的方式，无法获取到配置信息，这又是什么情况？

**Comment by fooololo** [comment]
已解决！

**Comment by verlen** [comment]
看不到实例的问题 如何解决

**Comment by 1310744545** [comment]
怎么解决的呢
