### ISSUE TITLE
DisconfFile用法咨询

### ISSUE THREAD

**Issue by nickle-ye** [knightliao/disconf#201]
在使用disconf的过程中，遇到下面的两个问题:
1. 自定义了“disconf.user_define_download_dir”的目录，可是disconf还是会把包里定义的“disconf.local_download_dir”也一样创建
   -->查了Issues, 说是会在2.6.37里优化，想明确一下，是否到时两个目录，只会创建其中一个目录，而且是“disconf.user_define_download_dir”的优先级大于“disconf.local_download_dir”
2. 在多个service类上使用了“@DisconfFile(filename = "resources.properties")”，这会导致在加载时报以下的错误：
   （这里用的版本2.6.34）

> 2016-10-19 17:05:05,015 [main] [ERROR] [com.baidu.disconf.client.store.inner.DisconfCenterStore.storeOneFile(DisconfCenterStore.java:73)] - There are two same fileName key!!!! first: 
>   DisconfCenterFile [
>   keyMaps={……}
>   cls=class cn.vhealth.user.web.service.TelefenService
>   fileName=resources.properties
>   copy2TargetDirPath=
>   DisconfCenterBaseModel [
>   object=null
>   remoteServerUrl=/api/config/file?app=user&env=rd&type=0&key=resources.properties&version=1.0
>   disConfCommonModel=DisConfCommonModel [app=vhealth-user, version=1.0, env=rd]
>   disconfCommonCallbackModel=DisconfCommonCallbackModel{disconfConfUpdates=[], disconfUpdatesActiveBackups=[]}]]
> , Second: 
>   DisconfCenterFile [
>   keyMaps={……}
>   cls=class cn.vhealth.user.web.service.MemberPackagesService
>   fileName=resources.properties
>   copy2TargetDirPath=
>   DisconfCenterBaseModel [
>   object=null
>   remoteServerUrl=/api/config/file?app=user&env=rd&type=0&key=resources.properties&version=1.0
>   disConfCommonModel=DisConfCommonModel [app=vhealth-user, version=1.0, env=rd]
>   disconfCommonCallbackModel=DisconfCommonCallbackModel{disconfConfUpdates=[], disconfUpdatesActiveBackups=[]}]]

是不是DisconfFile里的filename是不是要全局唯一(结合env,app,version)..
（如果是，可能在DisconfFile里加上对应的说明会比较好）

**Comment by fooololo** [comment]
There are two same fileName key!!!!  
这个不影响正常使用的。

**Comment by nickle-ye** [comment]
我知道不影响正常使用。但是日志上报的是error级别，这某种程度上是不合理的。
因为既然不影响使用，为什么要报error级别的错误。

而且这会增加使用者的成本，因为他们要去调查这error到底会不会影响功能的正常使用. (正常合理的应用是不应该存在任何error之上, 乃至warn级别的错误)

**Comment by fooololo** [comment]
如果是配置文件重复了，报的是WARN级别
如果是独立的配置项重复了，报的是ERROR级别

**Comment by nickle-ye** [comment]
呃……那我现在搞不清楚状况了，我在版本2.6.34里，在两个不同的class使用了“@DisconfFile(filename = "resources.properties")”。
我理解的是“配置文件重复”， 现在报的错误是ERROR（见上面的日志）。

**Comment by nickle-ye** [comment]
或者回到我上面的问题上，到底上面那个日志是不是正常的，或者说disconf是“倡导”，还是”明确”不给“在两个不同的class使用了@DisconfFile(filename = "resources.properties")”

**Comment by fooololo** [comment]
这个得 @knightliao  来解释了

**Comment by knightliao** [comment]
一个配置文件一个类是 disconf 倡导 的方式，不给 两个class同时使用同一个 "resources.properties"

**Comment by TrillStones** [comment]
有人说是因为springboot把配置文件也打包到jar文件里了
