### ISSUE TITLE
disconf wrong number of arguments

### ISSUE THREAD

**Issue by hitcold** [knightliao/disconf#206]
配置中配置了2个布尔型变量，报错wrong number of arguments，debug发现keMap里面有个布尔型的setMethod使用的是isXXX方法，导致了这个报错，最后将一个布尔型变量去掉了，只保留一个布尔型变量，则不再报错了，disconf版本号是2.6.34，不知各位有没有遇到和我一样的问题？？

**Comment by knightliao** [comment]
你的错误数据配置文件的内容是？
