### ISSUE TITLE
DisconfDataGetter支持读取disconf.ignore忽略的配置吗？

### ISSUE THREAD

**Issue by fooololo** [knightliao/disconf#209]
使用disconf.ignore忽略远程文件，在本地添加该文件后，DisconfDataGetter可以获取到文件里的配置吗？

**Comment by knightliao** [comment]
目前还不支持呢，你的诉求是什么？

**Comment by fooololo** [comment]
我向实现忽略远程文件，使用本地文件的时候，本地的配置也能使用disconf托管。
比如在使用远程文件的时候，我使用DisconfDataGetter获取配置，现在改成使用本地文件了，我还是可以通过DisconfDataGetter获取配置，而不需要修改代码。
