### ISSUE TITLE
release2.6.2版本缺少hadoop-v2

### ISSUE THREAD

**Issue by yinwer81** [knightliao/disconf#21]
如题，是3rd的包吗？google都没搜到。还有一些其他包比较难找。

**Comment by yinwer81** [comment]
另外，2.6.2都released this on 9 Jul 2014，什么时候release新版本啊？研究部署中。。。

**Comment by knightliao** [comment]
不要看那个地方，那个地方不准确的

现在的稳定版本是 2.6.24 
https://github.com/knightliao/disconf

**Comment by yinwer81** [comment]
谢谢，你不打tag或做release，怎么pull 2.6.24的代码？

**Comment by knightliao** [comment]
你说的确实是个问题，我下次版本 打上tag 来做 ：）
当前你可以直接用maven拉代码源码
