### ISSUE TITLE
上传不是UTF-8编码的文件时乱码

### ISSUE THREAD

**Issue by wanbx** [knightliao/disconf#212]
上传文件不是UTF-8编码集的文件时乱码
![image](https://cloud.githubusercontent.com/assets/20636383/19991684/6df12d3a-a272-11e6-8203-f0eff5d59745.png)

**Comment by tangshd** [comment]
为什么不用uat8编码

**Comment by knightliao** [comment]
最好使用 utf8 进行编码
因为 properties 就是 utf8编码的
