### ISSUE TITLE
Disconf Client使用中的两个问题

### ISSUE THREAD

**Issue by MicroCreativity** [knightliao/disconf#213]
# 1.每次启动都会抛出exists connect lost... will retry 0、exists connect lost... will retry 1、exists connect lost... will retry 2，为什么每次都要第四次才可以获取链接呢？请问什么原因？
![n8 ej 05cj3m4z3lmv 2](https://cloud.githubusercontent.com/assets/18007558/20015831/f6574d96-a2f7-11e6-9dd1-43f370af25ea.png)

# 2.There are two same fileName，打印出来的日志下载的文件是没内容的，为什么呢？
![1df7 tmp](https://cloud.githubusercontent.com/assets/18007558/20027415/267fc74e-a34f-11e6-819a-4a5189da564d.jpg)

**Comment by knightliao** [comment]
第一个问题， ZK集群的连接性不好
第二个问题  你同时使用了两种配置方式，（注解式 和 XML配置式），建议只使用一种方式
