### ISSUE TITLE
新建配置文件页面newconfig_file.html的问题

### ISSUE THREAD

**Issue by binarywang** [knightliao/disconf#22]
当有很多app时，app的下拉列表居然显示不全，请前端攻城师帮忙修复下吧，谢谢了！

**Comment by knightliao** [comment]
确实是个问题，回头我解决下

**Comment by knightliao** [comment]
这个下个版本就会修复

**Comment by knightliao** [comment]
https://github.com/knightliao/disconf/wiki/updates 已经修复了 使用2.6.27
