### ISSUE TITLE
多个工程依赖同一配置，如何做到只配一套

### ISSUE THREAD

**Issue by imsandy** [knightliao/disconf#221]
作者大哥，请教一下，什么时候出这种功能，在有A/B/C/D 多个项目时，依赖一些公共的配置，如何配置呢？需要只配置一套，而不是ABCD 每个里面有相同的配置，请问作者有做这个考虑吗？如果有，提供一下给我，不胜感激！

**Comment by SpringStudent** [comment]
https://github.com/SpringStudent/disconf.git,我这个可以

**Comment by 465996346** [comment]
https://github.com/465996346/disconf

1.添加一个app作为所有应用依赖的通用配置
例如：
![image](https://cloud.githubusercontent.com/assets/15191446/22640412/7089b9d0-ec8d-11e6-9973-25056afd717c.png)
这里添加了一个叫做common的应用。
2.在配置里面添加这几行配置
#通用app名称  默认common
disconf.common_app=common
#通用app版本
disconf.common_app_version=1_0_0_0
#通用app环境 默认与配置的app环境相同
disconf.common_app_env=
#通用app资源地址通配符
disconf.common_location_matches=common
3.spring配置
![image](https://cloud.githubusercontent.com/assets/15191446/22640496/daf6c6a0-ec8d-11e6-9889-a59b751422ab.png)
这里classpath*:/application-default.properties配置文件是在app名称为order_server的配置中心
classpath*:/common.properties该配置文件不在app名称为order_server的配置中心里面而在app名称为common的配置中心里面

**Comment by imsandy** [comment]
请问这个是新版本的功能吗？

**Comment by tianxiao-zp** [comment]
我们自己加的功能。目前正在用。

**Comment by tianxiao-zp** [comment]
有需要用的，可以给我留言，代码改动的话，可以在https://github.com/465996346/disconf中看到。
目前使用的环境在spring boot上面，目前运行正常。

**Comment by imsandy** [comment]
好的，灰常感谢了
