### ISSUE TITLE
请教容器决定env，下面部署多个contexts，context中定义app的配置

### ISSUE THREAD

**Issue by yinwer81** [knightliao/disconf#23]
如题，我们环境中，1个tomcat下面有多个war包，考虑在tomcat启动参数中配置env，下面各个war拉取该war中的配置。这样代码和配置分开以后，qa出来的代码可以直接进prod，请问现在是否已经支持，如何配置？

**Comment by knightliao** [comment]
你可以为你的tomcat设定启动参数就可以了，已经可以支持 https://github.com/knightliao/disconf/wiki/Tutorial9
