### ISSUE TITLE
version2.6.25   disconf-web AppNewForm代码缺少getter，setter

### ISSUE THREAD

**Issue by arebya** [knightliao/disconf#25]
如上

**Comment by knightliao** [comment]
hi, 新版的disconf采用了 lomock 来减少相应的 getter & setter代码
https://github.com/rzwitserloot/lombok

**Comment by licoco** [comment]
@knightliao  2.6.26大概什么时间发布啊，准备用用disconf
看了下更新日志，感觉下一个版本功能增强很多

**Comment by knightliao** [comment]
很多功能 都可能没有时间做，只是列出来要做的。
建议先用上 我们内部也在用 2.6.25
