### ISSUE TITLE
disconf高可用问题

### ISSUE THREAD

**Issue by gummike** [knightliao/disconf#252]
conf_server_host这个配置项是可以配置多个地址的。这样的话如果有好多应用，目前用了A，B两台disconf服务器，如果碰到disconf的扩容，这样得改所有的应用的配置，很麻烦。这个配置应该限制只能连接一个ip   ，server的高可用用nginx反向代理去做是不是更好

**Comment by knightliao** [comment]
一般在企业内部的做法是，设置内部域名，然后域名绑定多个IP，这样就不需要更改配置了。
