### ISSUE TITLE
数据库脚本没有同步增加字段role_id

### ISSUE THREAD

**Issue by uubu** [knightliao/disconf#27]
PO定义:
@Table(db = DB.DB_NAME, name = "user", keyColumn = Columns.USER_ID)
public class User extends BaseObject<Long> {

    private static final long serialVersionUID = 1L;

    // 唯一
    @Column(value = Columns.NAME)
    private String name;

    // token
    @Column(value = Columns.TOKEN)
    private String token;

    // 密码
    @Column(value = Columns.PASSWORD)
    private String password;

    //
    @Column(value = Columns.OWNAPPS)
    private String ownApps;

    /**
     * 角色ID
     */
    @Column(value = Columns.ROLE_ID)
    private int roleId;
    ...
}

数据库：
CREATE TABLE `user` (
    `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
    `name` VARCHAR(50) NOT NULL COMMENT '姓名',
    `password` VARCHAR(255) NOT NULL COMMENT '密码',
    `token` VARCHAR(255) NOT NULL COMMENT 'token',
    PRIMARY KEY (`user_id`)
)

**Comment by knightliao** [comment]
https://github.com/knightliao/disconf/blob/master/disconf-web/sql/20141226/disconf.sql  这里有进行修改

**Comment by uubu** [comment]
嗯，我本地修改后没有遇到什么大的问题！下个发布应该会合入吧？！
