### ISSUE TITLE
按照disconf-web/README.md部署以后无法登陆

### ISSUE THREAD

**Issue by uubu** [knightliao/disconf#28]
首先，感谢disconf的各位大牛的无私奉献，我的问题RT：

以下是我的部分分析：

我看到登陆请求为：/api/account/signin
那么按照README.md的步骤，nginx负责前端页面请求，tomcat负责后端业务逻辑处理，理论上这个已经是跨域；没有指定完整的请求路径则意味着/api/account/signin和login.html同属一个域，但实际上，两个服务器分别负责前后端则必然是不同的域，起码不可能同时在一个端口上启动监听，所以README.md部署说明和前端AJAX请求看起来是矛盾的。

所以请disconf的设计人员看看，这个是否有问题？

**Comment by knightliao** [comment]
hi, 没有跨域的。

nginx是监听80端口。tomcat是监听非80端口（例如是8080端口）。
通过nginx反向代理功能，就可以将 某域名（如disconf.com）解析到 8080端口上。

nginx 和 tomcat 均是 同一个域下

**Comment by uubu** [comment]
是的，我理解错了！

**Comment by chenhuan888** [comment]
你们部署好以后可以登录吗  为什么我的不行？http://xxx.xxx.xxx.xxx:8090/api/account/signin 404 (Not Found)
