### ISSUE TITLE
disconf-web不支持分布式么？

### ISSUE THREAD

**Issue by wenskys** [knightliao/disconf#283]
hi，disconf.properties中定义了host可以用,分隔，但实际上我测试的时候挂了一台，服务是已经不可用的了，这个不是的理解不是应该是支持分布式的么？
```
# 配置服务器的 HOST,用逗号分隔127.0.0.1:8000,127.0.0.1:8000
conf_server_host=127.0.0.1:8000,127.0.0.1:8081
```

**Comment by yzzh9** [comment]
conf_server_host=集群地址

**Comment by wenskys** [comment]
@yzzh9 测试的时候不够细心，没仔细看日志，是支持的

**Comment by seven7ma** [comment]
我一台机器配置了两台disconf实例,conf_server_host=配置的是nginx的地址,
nginx配置: 
 upstream disconf 
{
      server 127.0.0.1:8015;
      server 127.0.0.1:8016;
}
.两台实例都开启时,disconf界面会不停的在登录界面和首页间切换,
8015的机器日志:
309feb2d-fd3d-4aa3-adc5-d762d1f4b40c 2018-04-10 18:37:30,561 [http-nio-8015-exec-4] INFO  com.baidu.dsp.common.interceptor.login.LoginInterceptor - /api/account/session
309feb2d-fd3d-4aa3-adc5-d762d1f4b40c 2018-04-10 18:37:30,562 [http-nio-8015-exec-4] INFO  com.baidu.dsp.common.vo.JsonObjectUtils - JsonObject(result={visitor=VisitorVo [id=6, name=admin, role=null]})
93dd3407-11a1-4ba0-9345-7427f725171f 2018-04-10 18:37:30,826 [http-nio-8015-exec-3] INFO  com.baidu.dsp.common.interceptor.login.LoginInterceptor - /api/app/list
93dd3407-11a1-4ba0-9345-7427f725171f 2018-04-10 18:37:30,827 [http-nio-8015-exec-3] INFO  com.baidu.disconf.web.service.roleres.service.RoleResourceAspect - Accessing URL:/api/app/list/, method:GET, UserId:6, RoleId:2, Is priviledged:true
93dd3407-11a1-4ba0-9345-7427f725171f 2018-04-10 18:37:30,833 [http-nio-8015-exec-3] INFO  com.baidu.dsp.common.vo.JsonObjectUtils - JsonObjectBase [message={}, sessionId=93dd3407-11a1-4ba0-9345-7427f725171f, success=true]
不停循环打印,另一台机控制台无输出

redis 是单机的设置了密码.

**Comment by seven7ma** [comment]
求解

**Comment by wenskys** [comment]
@seven7ma 换apollo吧，我们已经把disconf抛弃了

**Comment by seven7ma** [comment]
谢谢
