### ISSUE TITLE
disconf现在已经不怎么维护了，还能实现灰度模式么

### ISSUE THREAD

**Issue by wenskys** [knightliao/disconf#292]
disconf现在已经不怎么维护了，作者也不见人影了，现在还能实现灰度模式么

**Comment by Alexdevlin** [comment]
不是吧？??还准备采用呢

**Comment by wenskys** [comment]
@Alexdevlin 使用的话还是可以的，他默认是下发服务，然后重启生效，这个有点类似于灰度吧，但不应该叫灰度。

**Comment by wxdh1987** [comment]
有人用过携程的apollo吗？我们现在的配置中心也支持灰度

**Comment by wenskys** [comment]
@wxdh1987 用apollo的灰度么？

**Comment by wxdh1987** [comment]
apollo本身是通过版本支持灰度的，但是在disconf中好像没找到类似的功能，因为我们业务需要，灰度功能必不可少，所以新项目想试点apollo，如果有人在disconf上发现类似的功能或者自己扩展的，也希望不吝赐教。

**Comment by francisoliverlee** [comment]
因为我也有相同的需求， 自己做了个二次开发。 可以按照ip灰度
http://git.oschina.net/youlixishi/disconf
