### ISSUE TITLE
disconf-web创建新的app失败

### ISSUE THREAD

**Issue by wjwujing** [knightliao/disconf#30]
在AppController 的方法  JsonObjectBase create(@Valid AppNewForm appNewForm) 中 发现 从web前端传过来的appNewForm 为空对象。 还需要修改其他的 配置信息吗？

**Comment by wjwujing** [comment]
不知是否和 HttpPutFormContentFilter 过滤器和 Tomcat版本有关系，已实验修改 method = RequestMethod.POST PUT ，结果是 NullException 异常。

**Comment by uubu** [comment]
看起来这个@Valid实际上会对入参进行检查，可以好好看看这个参数是否合法，可能是因为检查没有通过导致功能不可用。
