### ISSUE TITLE
可以考虑不指定PO的DB字段，同时升级缺省的mysql驱动

### ISSUE THREAD

**Issue by uubu** [knightliao/disconf#31]
Hi，我认为指定了PO的DB字段就限制了数据库名字，使用上不太方便。我在部署第一套环境的时候已经创建了数据库（名称不是disconf），这会导致功能不可用。可以考虑在jdbc-mysql.properties中直接指定url就行，这样可以进一步放宽使用限制。另外，disconf缺省使用的是mysql的connector，这个遵循的开源协议时GPL，建议改成mariadb，这个遵循的Apache License 2.0开源协议，目前使用mariadb的用户应该更多。

**Comment by knightliao** [comment]
从业界主流来看，mariadb应该没有mysql主流。
jdbc-mysql.properties 不指定 数据库名，我认为 会更加open点，这样你在代码中可以使用更多的db名进行处理
