### ISSUE TITLE
mvn clean install 失败

### ISSUE THREAD

**Issue by xingguanghui** [knightliao/disconf#317]
70 个错误
100 个警告
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] disconf ........................................... SUCCESS [33.721s]
[INFO] disconf-core ...................................... FAILURE [49.214s]
[INFO] disconf-client .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:23.493s
[INFO] Finished at: Wed Jun 14 08:19:29 CST 2017
[INFO] Final Memory: 38M/294M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (attach-javadocs) on project disconf-core: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/WriteLock.java:267: 警告: 没有 @return
[ERROR] public synchronized boolean lock() throws KeeperException, InterruptedException {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/WriteLock.java:267: 警告: org.apache.zookeeper.KeeperException没有 @throws
[ERROR] public synchronized boolean lock() throws KeeperException, InterruptedException {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/WriteLock.java:267: 警告: java.lang.InterruptedException没有 @throws
[ERROR] public synchronized boolean lock() throws KeeperException, InterruptedException {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/WriteLock.java:289: 警告: 没有 @return
[ERROR] public boolean isOwner() {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/WriteLock.java:36: 错误: 不允许使用自关闭元素
[ERROR] * write lock or to elect a leader</a>. <p/> You invoke {@link #lock()} to
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/WriteLock.java:38: 错误: 不允许使用自关闭元素
[ERROR] * some time later. <p/> You can register a listener so that you are invoked
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/WriteLock.java:59: 错误: @param name 未找到
[ERROR] * @param acls      the acls that you want to use for all the paths,
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/WriteLock.java:62: 警告: acl没有 @param
[ERROR] public WriteLock(ZooKeeper zookeeper, String dir, List<ACL> acl) {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/ProtocolSupport.java:151: 警告: @param 没有说明
[ERROR] * @param path
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/ProtocolSupport.java:152: 警告: @param 没有说明
[ERROR] * @param acl
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/ProtocolSupport.java:153: 警告: @param 没有说明
[ERROR] * @param flags
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/ProtocolSupport.java:155: 警告: data没有 @param
[ERROR] protected void ensureExists(final String path, final byte[] data, final List<ACL> acl, final CreateMode flags) {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/ProtocolSupport.java:142: 警告: @param 没有说明
[ERROR] * @param path
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/ProtocolSupport.java:118: 警告: operation没有 @param
[ERROR] protected Object retryOperation(ZooKeeperOperation operation) throws KeeperException, InterruptedException {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/ProtocolSupport.java:118: 警告: org.apache.zookeeper.KeeperException没有 @throws
[ERROR] protected Object retryOperation(ZooKeeperOperation operation) throws KeeperException, InterruptedException {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/ProtocolSupport.java:118: 警告: java.lang.InterruptedException没有 @throws
[ERROR] protected Object retryOperation(ZooKeeperOperation operation) throws KeeperException, InterruptedException {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/ZooKeeperOperation.java:34: 警告: @throws 没有说明
[ERROR] * @throws KeeperException
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/org/apache/zookeeper/recipes/lock/ZooKeeperOperation.java:35: 警告: @throws 没有说明
[ERROR] * @throws InterruptedException
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/impl/RestfulMgrImpl.java:44: 警告: @param 没有说明
[ERROR] * @param clazz
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/impl/RestfulMgrImpl.java:45: 警告: @param 没有说明
[ERROR] * @param remoteUrl
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/impl/RestfulMgrImpl.java:47: 警告: @return 没有说明
[ERROR] * @return
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/impl/RestfulMgrImpl.java:49: 警告: @throws 没有说明
[ERROR] * @throws Exception
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/impl/RestfulMgrImpl.java:83: 警告: @param 没有说明
[ERROR] * @param retryTimes
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/impl/RestfulMgrImpl.java:84: 警告: @param 没有说明
[ERROR] * @param retrySleepSeconds
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/impl/RestfulMgrImpl.java:86: 警告: @return 没有说明
[ERROR] * @return
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/impl/RestfulMgrImpl.java:88: 警告: @throws 没有说明
[ERROR] * @throws Exception
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulMgr.java:16: 警告: @param 没有说明
[ERROR] * @param clazz
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulMgr.java:17: 警告: @param 没有说明
[ERROR] * @param remoteUrl
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulMgr.java:19: 警告: @return 没有说明
[ERROR] * @return
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulMgr.java:21: 警告: @throws 没有说明
[ERROR] * @throws Exception
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulMgr.java:23: 警告: <T>没有 @param
[ERROR] <T> T getJsonData(Class<T> clazz, RemoteUrl remoteUrl, int retryTimes, int retrySleepSeconds) throws Exception;
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulMgr.java:23: 警告: retryTimes没有 @param
[ERROR] <T> T getJsonData(Class<T> clazz, RemoteUrl remoteUrl, int retryTimes, int retrySleepSeconds) throws Exception;
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulMgr.java:23: 警告: retrySleepSeconds没有 @param
[ERROR] <T> T getJsonData(Class<T> clazz, RemoteUrl remoteUrl, int retryTimes, int retrySleepSeconds) throws Exception;
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulMgr.java:33: 警告: @throws 没有说明
[ERROR] * @throws Exception
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulMgr.java:35: 警告: localFileDirTemp没有 @param
[ERROR] String downloadFromServer(RemoteUrl remoteUrl, String fileName, String localFileDir, String localFileDirTemp,
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulMgr.java:35: 警告: enableLocalDownloadDirInClassPath没有 @param
[ERROR] String downloadFromServer(RemoteUrl remoteUrl, String fileName, String localFileDir, String localFileDirTemp,
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulMgr.java:35: 警告: retryTimes没有 @param
[ERROR] String downloadFromServer(RemoteUrl remoteUrl, String fileName, String localFileDir, String localFileDirTemp,
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulMgr.java:35: 警告: retrySleepSeconds没有 @param
[ERROR] String downloadFromServer(RemoteUrl remoteUrl, String fileName, String localFileDir, String localFileDirTemp,
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulFactory.java:15: 警告: @return 没有说明
[ERROR] * @return
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/RestfulFactory.java:17: 警告: @throws 没有说明
[ERROR] * @throws Exception
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/retry/impl/RetryStrategyRoundBin.java:20: 警告: @param 没有说明
[ERROR] * @param unreliableImpl
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/retry/impl/RetryStrategyRoundBin.java:21: 警告: @param 没有说明
[ERROR] * @param retryTimes
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/retry/impl/RetryStrategyRoundBin.java:22: 警告: @param 没有说明
[ERROR] * @param sleepSeconds
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/type/FetchConfFile.java:28: 警告: @param 没有说明
[ERROR] * @param remoteUrl
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/restful/type/FetchConfFile.java:29: 警告: @param 没有说明
[ERROR] * @param localTmpFile
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:33: 错误: @return 的用法无效
[ERROR] * @return void
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:35: 警告: @throws 没有说明
[ERROR] * @throws Exception
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:36: 错误: 未知标记: Description
[ERROR] * @Description: 初始化
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:38: 错误: 未知标记: date
[ERROR] * @date 2013-6-14
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:40: 警告: host没有 @param
[ERROR] public void init(String host, String defaultPrefixString, boolean debug) throws Exception {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:40: 警告: defaultPrefixString没有 @param
[ERROR] public void init(String host, String defaultPrefixString, boolean debug) throws Exception {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:40: 警告: debug没有 @param
[ERROR] public void init(String host, String defaultPrefixString, boolean debug) throws Exception {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:109: 警告: @param 没有说明
[ERROR] * @param dir
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:111: 警告: data没有 @param
[ERROR] public void makeDir(String dir, String data) {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:133: 错误: @return 的用法无效
[ERROR] * @return void
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:135: 错误: 未知标记: Description
[ERROR] * @Description: 应用程序必须调用它来释放zookeeper资源
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:137: 错误: 未知标记: date
[ERROR] * @date 2013-6-14
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:139: 警告: java.lang.InterruptedException没有 @throws
[ERROR] public void release() throws InterruptedException {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:145: 错误: 未知标记: String
[ERROR] * @return List<String>
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:147: 错误: 未知标记: Description
[ERROR] * @Description: 获取子孩子 列表
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:149: 错误: 未知标记: date
[ERROR] * @date 2013-6-14
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:157: 错误: @return 的用法无效
[ERROR] * @return List<String>
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:157: 错误: 未知标记: String
[ERROR] * @return List<String>
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:159: 错误: 未知标记: Description
[ERROR] * @Description: 写持久化结点, 没有则新建, 存在则进行更新
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:161: 错误: 未知标记: date
[ERROR] * @date 2013-6-14
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:163: 警告: url没有 @param
[ERROR] public void writePersistentUrl(String url, String value) throws Exception {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:163: 警告: value没有 @param
[ERROR] public void writePersistentUrl(String url, String value) throws Exception {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:163: 警告: java.lang.Exception没有 @throws
[ERROR] public void writePersistentUrl(String url, String value) throws Exception {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:169: 错误: 未知标记: String
[ERROR] * @return List<String>
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:171: 错误: 未知标记: Description
[ERROR] * @Description: 读结点数据
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:173: 错误: 未知标记: date
[ERROR] * @date 2013-6-14
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:175: 警告: url没有 @param
[ERROR] public String readUrl(String url, Watcher watcher) throws Exception {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:175: 警告: watcher没有 @param
[ERROR] public String readUrl(String url, Watcher watcher) throws Exception {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:175: 警告: java.lang.Exception没有 @throws
[ERROR] public String readUrl(String url, Watcher watcher) throws Exception {
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:205: 警告: @param 没有说明
[ERROR] * @param path
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:206: 警告: @param 没有说明
[ERROR] * @param watcher
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:207: 警告: @param 没有说明
[ERROR] * @param stat
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:211: 警告: @throws 没有说明
[ERROR] * @throws InterruptedException
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:212: 警告: @throws 没有说明
[ERROR] * @throws KeeperException
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:213: 错误: 未知标记: Description
[ERROR] * @Description: 带状态信息的读取数据
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:215: 错误: 未知标记: date
[ERROR] * @date 2013-6-17
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:223: 警告: @param 没有说明
[ERROR] * @param path
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:225: 错误: @return 的用法无效
[ERROR] * @return void
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:227: 错误: 未知标记: Description
[ERROR] * @Description: 删除结点
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/ZookeeperMgr.java:229: 错误: 未知标记: date
[ERROR] * @date 2013-6-17
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/inner/ConnectionWatcher.java:46: 警告: @param 没有说明
[ERROR] * @param hosts
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/inner/ConnectionWatcher.java:48: 错误: @return 的用法无效
[ERROR] * @return void
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/inner/ConnectionWatcher.java:50: 警告: @throws 没有说明
[ERROR] * @throws IOException
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/inner/ConnectionWatcher.java:51: 警告: @throws 没有说明
[ERROR] * @throws InterruptedException
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/inner/ConnectionWatcher.java:52: 错误: 未知标记: Description
[ERROR] * @Description: 连接ZK
[ERROR] ^
[ERROR] /home/project/disconf/disconf-core/src/main/java/com/baidu/disconf/core/common/zookeeper/inner/ConnectionWatcher.java:54: 错误: 未知标记: date

**Comment by sichengLv** [comment]
同求解决~

**Comment by xjzrc** [comment]
mvn clean install -Dadditionalparam=-Xdoclint:none

**Comment by yizhiyao** [comment]
进入pom文件删除javadoc的插件

**Comment by langke93** [comment]
@xjzrc 方法有效，困扰已久问题解决了

**Comment by xingguanghui** [comment]
3Q

**Comment by shenjiefeng** [comment]
> 进入pom文件删除javadoc的插件

正解，删除就好了。去掉javadoc提示仍然一堆错误
