### ISSUE TITLE
数据库role_resource没有同步创建

### ISSUE THREAD

**Issue by uubu** [knightliao/disconf#33]
目前sql脚本没有自动生成role_resource表，手动创建该表以后提示没有权限访问资源。目前初步分析是这样，还没有继续往下分析。以下是请求log：
ca53fa30-0ed0-4632-a858-8fd11a41dd9a 2015-09-21 16:01:48,684 [http-bio-8080-exec-2] INFO  com.baidu.dsp.common.interceptor.login.LoginInterceptor - /api/app
ca53fa30-0ed0-4632-a858-8fd11a41dd9a 2015-09-21 16:01:48,688 [http-bio-8080-exec-2] INFO  com.baidu.disconf.web.service.roleres.service.impl.RoleResourceMgrImpl - Querying role_resource table to get all...
ca53fa30-0ed0-4632-a858-8fd11a41dd9a 2015-09-21 16:01:48,688 [http-bio-8080-exec-2] INFO  com.baidu.dsp.common.dao.AbstractDao - ----null	disconf.role_resource
ca53fa30-0ed0-4632-a858-8fd11a41dd9a 2015-09-21 16:01:48,688 [http-bio-8080-exec-2] INFO  com.baidu.dsp.common.dao.AbstractDao - select method_mask,role_id,update_time,role_res_id,url_description,url_pattern from disconf.role_resource	[]
ca53fa30-0ed0-4632-a858-8fd11a41dd9a 2015-09-21 16:01:48,701 [http-bio-8080-exec-2] WARN  com.baidu.dsp.common.handler.MyExceptionHandler - /api/app ExceptionHandler FOUND. com.baidu.dsp.common.exception.AccessDeniedException	null
ca53fa30-0ed0-4632-a858-8fd11a41dd9a 2015-09-21 16:01:48,702 [http-bio-8080-exec-2] WARN  com.baidu.dsp.common.handler.MyExceptionHandler - details: Access Denied: /api/app/, method:POST, UserId:1, RoleId:1

**Comment by knightliao** [comment]
https://github.com/knightliao/disconf/tree/master/disconf-web/sql 请先执行以下SQL
