### ISSUE TITLE
关于disconf 自动reload property 的支持范围

### ISSUE THREAD

**Issue by winjeg** [knightliao/disconf#331]
在运行的时候
1. 构造方法里面引用 properties    
```
<bean id="name" class="java.lang.String">
        <constructor-arg value="${name}"></constructor-arg>
</bean>
```
2. 在一些 有 Pool 的Client 里面比如 redis,  mysql 的连接池， 如果 property 文件更新了，
这些连接池里面的连接会更新么？

**Comment by felix3210** [comment]
貌似不会自动更新，properties文件可以下载到本地classpath、xml中属性不会reload

**Comment by winjeg** [comment]
我查看了它的源代码， 是肯定不会更新的， 是构造函数里面的，调用就相当于重新构造对象， 都不是同一个对象了， 肯定不会更新的.

**Comment by promission** [comment]
@winjeg  你好，我想问下你构造方法中使用$变量，项目启动不会报找不到这个变量吗？ disconf这个时候还没有去加载配置吧
