### ISSUE TITLE
权限检查不通过，无法添加新的应用

### ISSUE THREAD

**Issue by uubu** [knightliao/disconf#34]
Hi，手动创建了数据表role/role_resource并增加了记录进行关联，METHOD_MASK改为0123，记录如下：
0	0	/api/app		0123	2015-09-21 16:18:10
发现代码中下面这行：
public static final char METHOD_IS_ACCESSIBLE = '1';
只允许访问方法PUT，这是什么缘故？

看代码，上述配置在解析时只会把PUT方法加入缓存，当前台视图创建APP的时候发现是POST方法，无法通过检查，莫非这是disconf有意为之？

**Comment by knightliao** [comment]
0 0 /api/app 0123 2015-09-21 16:18:10  
你这个格式有问题
