### ISSUE TITLE
war包部署的问题

### ISSUE THREAD

**Issue by zippoer** [knightliao/disconf#37]
hi，我按照disconf-web/README中的步骤部署。其中配置文件我是从disconf/disconf-web/src/main/resources目录下拷贝过来的。更改了其中jdbc-mysql.properties的jdbc.db_0.username、jdbc.db_0.password。redis-config.properties文件我没看明白，因为我司redis都不需要密码的，为了适配这个文件，我也在redis.conf中requirepass foobared。另外，没看懂redis.group1.client1.name和redis.group1.client2.name这个怎么设置？rabbit.properties中修改了username和password，使用的是如下root用户，这样配置是否有错？
![image](https://cloud.githubusercontent.com/assets/7703213/10600592/64b1960c-773e-11e5-94b5-06fb16a5f00b.png)
zoo.properties没有修改。
P.S.上述所有基础服务我是部署在一台虚拟机上，不知这样配置是否有错？
然后用admin登陆网页，显示“服务器内部错误”。
新手提问，比较业余，求不喷^-^。谢谢各位技术大佬！

**Comment by knightliao** [comment]
redis.group1.client2.name 这个随便设置就可以啦
rabbit.properties 可以不用管，如果不想订阅日志的话
redis如果没有密码，就放空就行了
