### ISSUE TITLE
按照文档步骤 到打包时异常

### ISSUE THREAD

**Issue by seven7ma** [knightliao/disconf#379]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:03 min
[INFO] Finished at: 2018-03-23T03:07:39-04:00
[INFO] Final Memory: 37M/95M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:jar (attach-javadocs) on project disconf-web: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - /usr/local/develop/disconf/src/disconf-web/src/main/java/com/baidu/disconf/web/common/email/MailSenderInfo.java:40: warning: no @return
[ERROR] public Properties getProperties() {

**Comment by seven7ma** [comment]
配置文件在 /usr/local/develop/disconf/resource 存放 
ONLINE_CONFIG_PATH=/usr/local/develop/disconf/resource

环境变量配置
WAR_ROOT_PATH=/usr/local/develop/disconf/war
export ONLINE_CONFIG_PATH
export WAR_ROOT_PATH

**Comment by luffy3546** [comment]
使用的是jdk8吗？是的话暂时切到jdk7试试，后续修复这个

**Comment by seven7ma** [comment]
好的

**Comment by seven7ma** [comment]
可以了，真的非常感谢。
