### ISSUE TITLE
Using Lombok in Disconf

### ISSUE THREAD

**Issue by knightliao** [knightliao/disconf#38]
为减少POJO中少写Getter，Setter，框架使用Lombok库。开发时需要在IDE中配置Lombok插件。
参见：http://codepub.cn/2015/07/30/Lombok-development-guidelines/

**Comment by shuaicong** [comment]
？？想问下怎么配合 @DisconfFileItem 使用？

**Comment by smartwuwei** [comment]
为什么使用disconf-web提示我频繁登录？

**Comment by daxiaoli123** [comment]
本地启动 中途就不动了
