### ISSUE TITLE
添加配置项异常

### ISSUE THREAD

**Issue by slimina** [knightliao/disconf#39]
当添加配置的value有字符"/"

disconf-web 无法正常显示

|----/disconf/redis-demo_1.0.0_local
	|----file
		|----redis.properties
			|----slimina_0_dab369bc-7834-4ad4-8c3c-8004dddefd37	{"redis.host":"192.168.1.90","redis.port":6379}
	|----item
		|----user.name
			|----slimina_0_dab369bc-7834-4ad4-8c3c-8004dddefd37	tomcater\

**Comment by knightliao** [comment]
我try了一下，貌似没有这个问题啊，能否描述具体点？
