### ISSUE TITLE
JavaBean property 'locations' being accessed! Ambiguous write methods found next to actually used 

### ISSUE THREAD

**Issue by markyao** [knightliao/disconf#43]
因bean **`ReloadablePropertiesFactoryBean`** 有属性locations和 Spring中的**`PropertyPlaceholderConfigurer`**属性有冲突，在启动的时候经常出现下面警告，如果出现警告连接不到web后台配置

**WARN  GenericTypeAwarePropertyDescriptor:116 - Invalid JavaBean property 'locations' being accessed! Ambiguous write methods found next to actually used [public void com.baidu.disconf.client.addons.properties.ReloadablePropertiesFactoryBean.setLocations(java.util.List)]: [public void org.springframework.core.io.support.PropertiesLoaderSupport.setLocations(org.springframework.core.io.Resource[])**

**Comment by hesy007** [comment]
这个问题怎么解决的？

**Comment by guangqan** [comment]
解决了吗

**Comment by knightliao** [comment]
这个警告是可预期的，不必担心
