### ISSUE TITLE
想知道用disconf 基于spring-boot的用户多不多

### ISSUE THREAD

**Issue by xuminwlt** [knightliao/disconf#44]
正在集成，想知道下同伴们的情况，碰到问题好探讨。

**Comment by knightliao** [comment]
具体demo可以见这里。https://github.com/knightliao/disconf-demos-java

我认为spring boot目前可能还不是很流行，但是他是未来，迟早都要变过去的。

**Comment by chenkline** [comment]
@knightliao 请问一下，disconf后续是否能考虑直接支持spring-boot的@ConfigurationProperties(prefix = "spring.datasource")这类注解？ 而不是仅仅支持@DisconfFile(filename = "simple.properties")的注解？
