### ISSUE TITLE
login.html中点击登录无响应

### ISSUE THREAD

**Issue by zyh12061225** [knightliao/disconf#46]
查看浏览器信息显示 POST /api/account/singin : 404 not found
请问是什么原因？

还有如何开启调试？

**Comment by DougLee** [comment]
您好，请问登录无响应这个问题最后是怎么解决的？

**Comment by zyh12061225** [comment]
您好，这个问题过去太久了，您检查一下mysql、redis、zookeeper是否正确安装，还有配置文件的目录、配置信息是否正确（参考https://github.com/knightliao/disconf/tree/master/disconf-web中的How to deploy）。我的问题是配置文件引起的。
