### ISSUE TITLE
是否可以不把配置Copy到classpath中？

### ISSUE THREAD

**Issue by orika** [knightliao/disconf#47]
目前，disconf启动的时候会把配置文件Copy一份到class path中，是否支持配置不Copy到class path中?
disconf.enable_local_download_dir_in_class_path 这个配置不能生效！

为了线上应用的安全性，数据库密码和其它配置的信息都是保密的，一般会把配置放在一个一般用户没有权限的目录下，而应用对一般有用是开放的，如果配置被copy到classpath下，安全性大大降低。

是否考虑支持该特性？从user_define_download_dir加载配置，而不是Copy到class path

**Comment by knightliao** [comment]
1. 你可以设置成数据库用户名密码只能本台机器才能登录使用，这样即使知道也无法操作。  2. 从非classpath读取的话会被考虑使用，而且正在做之中。 3. https://github.com/knightliao/disconf/wiki/Tutorial11-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%B8%8B%E8%BD%BD%E5%9C%B0%E5%9D%80%E8%AE%A8%E8%AE%BA 你可以使用注解式 @DisconfFile 的 copy2TargetDirPath 这样会从指定路径load配置。XML的方式后续会提供

**Comment by orika** [comment]
1条件基本不满足，线上机器可能动态扩容，每次都要更改数据库的权限
2这个我代码写了一部分，自测Ok，还没进行正式测试

**Comment by knightliao** [comment]
你可以使用 disconf.enable_local_download_dir_in_class_path=false 来禁止放到classpath里，然后 注解的目前已经支持
