### ISSUE TITLE
部署文档好像有点简单

### ISSUE THREAD

**Issue by wangjild** [knightliao/disconf#49]
比如tomcat的详细配置。6，7，8每个版本的配置都不太一样，能否说明是在哪个版本下。
比如文档中的 application.demo.properties这些配置文件样例模板在哪copy之类的。

按照部署文档折腾一上午啦。

**Comment by orika** [comment]
部署确实有点麻烦，作者能够简化下部署？现在还依赖Nginx，改配置
我自己用的时候，对文件目录做了较大的改动，才能直接扔到Tomcat里面跑

**Comment by yuankui** [comment]
有部署文档吗??
找了半天都没找到...

**Comment by knightliao** [comment]
我最近尽量简化下，辛苦大家了

**Comment by Yizener** [comment]
按照文档部署，点击登录 没有反应！

**Comment by Misfit-John** [comment]
同按照文档部署，点了登陆没有反应。应该是mysql啥的没连接上。但是文档并没有告诉我哪里找这玩意啊。满世界寻找中。

**Comment by georgezouq** [comment]
@orika  怎么改的 ??
