### ISSUE TITLE
web模块是不是缺少一套缺省的properties的配置文件

### ISSUE THREAD

**Issue by phantomes** [knightliao/disconf#50]
lz你好，在disconf-web的部署说明那部分里，说道：

配置文件包括：
- jdbc-mysql.properties (数据库配置)
- redis-config.properties (Redis配置)
- zoo.properties (Zookeeper配置)
- application.properties (应用配置）

我在想是不是有一套缺省配置的demo，好让大家可以对着properties的key配置自己的环境，
如果没有这样4个示例文件的话，而是自己各自填的话，lz的程序启动时，怎么读取db信息，zk信息，redis信息等等，上群里问了下，没人搭理，只要来提iss，望lz见谅~~~

**Comment by knightliao** [comment]
hi, https://github.com/knightliao/disconf/tree/master/disconf-web/src/main/resources 这里有所有配置的demo配置，你可以参考下
