### ISSUE TITLE
貌似发现个bug

### ISSUE THREAD

**Issue by wanglei1598** [knightliao/disconf#51]
设置disconf.enable_local_download_dir_in_class_path=false之后， @DisconfFile(filename = "")如果不设置已copy2TargetDirPath，仍会从classpath下面读取 配置。然后找不到。注入不了值，获取不到配置。

**Comment by knightliao** [comment]
你这样设置的目的是什么呢？这个配置文件就放着不读取是吗？

**Comment by wanglei1598** [comment]
我不想从默认的classpath。我想从download配置文件的路径读。但我这样就必须要指定copy2TargetDirPath才可以。这样就造成了硬编码……  还有一个问题。我已经暂时不考虑注解的形式了。使用XML的形式。如果使用非properties的配置文件。我的文件更新了，我如何获取新文件的内容。现在支持这种功能了吗？

**Comment by knightliao** [comment]
已经支持了https://github.com/knightliao/disconf/wiki/Tutorial8
