### ISSUE TITLE
Disconf 一处硬编码问题com.baidu.disconf.core.common.restful.impl.RestfulMgrImpl  

### ISSUE THREAD

**Issue by wanglei1598** [knightliao/disconf#53]
com.baidu.disconf.core.common.restful.impl.RestfulMgrImpl  
private File retryDownload(String fileName, RemoteUrl remoteUrl, int retryTimes, int retrySleepSeconds)
            throws Exception {

        String tmpFileDir = "./disconf/download";   //为什么要硬编码………………  有没有考虑到可能有问题
        String tmpFilePath = OsUtil.pathJoin(tmpFileDir, fileName);
        String tmpFilePathUnique = MyStringUtils.getRandomName(tmpFilePath);
        File tmpFilePathUniqueFile = new File(tmpFilePathUnique);
        retry4ConfDownload(remoteUrl, tmpFilePathUniqueFile, retryTimes, retrySleepSeconds);

        return tmpFilePathUniqueFile;
    }

**Comment by knightliao** [comment]
在sys配置文件里有，我没有用上。https://github.com/knightliao/disconf/blob/master/disconf-client/src/main/resources/disconf_sys.properties
我下个版本 fix，感谢提醒

**Comment by knightliao** [comment]
fix
