### ISSUE TITLE
配置中版本号是否可以使用1.0.0.0的格式？

### ISSUE THREAD

**Issue by eisig** [knightliao/disconf#54]
https://github.com/knightliao/disconf/wiki/%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E
中提到版本号要使用1_0_0_0的版本？请问使用1.0.0.0的格式是否可以？ Demo试了一下是可以的， 是否会引起其他问题？

**Comment by knightliao** [comment]
目前应该是没有问题的
