### ISSUE TITLE
本地拉取配置enable.remote.conf=false好像有问题？

### ISSUE THREAD

**Issue by WillWang2015** [knightliao/disconf#57]
我在项目中配置了`enable.remote.conf=false`。然后将所有的配置文件放在classpath下面，**确认文件都是齐全的**。
项目中配置了两种读取方式，一种是分布式annotation托管，一种是静态托管。配置如下：
```
    <context:component-scan base-package="com.xxx.product"/>

    <aop:aspectj-autoproxy proxy-target-class="true"/>

    <!-- 使用disconf必须添加以下配置 -->
    <bean id="disconfMgrBean" class="com.baidu.disconf.client.DisconfMgrBean"
          destroy-method="destroy">
        <property name="scanPackage" value="com.xxx.product"/>
    </bean>
    <bean id="disconfMgrBean2" class="com.baidu.disconf.client.DisconfMgrBeanSecond"
          init-method="init" destroy-method="destroy">
    </bean>

    <bean id="configproperties_no_reloadable_disconf"
          class="com.baidu.disconf.client.addons.properties.ReloadablePropertiesFactoryBean">
        <property name="locations">
            <list>
                <value>classpath:/xxx.properties</value>
                ...
            </list>
        </property>
    </bean>

    <bean id="propertyConfigurer"
          class="org.springframework.beans.factory.config.PropertyPlaceholderConfigurer">
        <property name="ignoreResourceNotFound" value="false"/>
        <property name="ignoreUnresolvablePlaceholders" value="true"/>
        <property name="propertiesArray">
            <list>
                <ref bean="configproperties_no_reloadable_disconf"/>
            </list>
        </property>
    </bean>
```

通过debug信息，并追踪了disconf的初始化过程，发现第一次扫描已经根据`DisClientConfig.getInstance().ENABLE_DISCONF`读取到并加载了正确的本地配置。
静态托管的文件都没有问题，应用可以读取到本地配置文件。
annotation托管的配置实例Bean的配置项属性值运行中都为null。

没找到原因。这是个bug吗？

**Comment by WillWang2015** [comment]
找到原因了，`DisconfAspectJ`只会在`enable.remote.conf=true`的时候才会进行切面。
配置Bean加上`@DisconfFile`后已经变为一个proxy bean,这样读取的配置就不能被正确注入，所以都是null。
难道annotation的bean不能使用本地配置？不解。

**Comment by WillWang2015** [comment]
验证发现，把所有的静态的，动态托管的配置文件放在本地classpath，设置`enable.remote.conf=true`。
`conf_server_host`设置为一个错误的地址，这样才能都正确使用本地的配置运行。
@knightliao 能否解释下这个问题。
因为有很多配置项，开发人员每个人都有自己的环境，配置项会不同。我希望所有的配置文件都放在本地classpath中，作为Local开发配置，可以个人修改。其他环境使用disconf远程配置。

**Comment by knightliao** [comment]
hi 功能上应该是没有问题的。
1. 因为配置bean实例的field亦会被注入值，即便配置Bean加上@DisconfFile后已经变为一个proxy bean,也可以正确找到对应的bean并注入
2. 你可以跑下 https://github.com/knightliao/disconf-demos-java/tree/master/disconf-standalone-demo 这个demo试试？把配置下下来，然后本地跑试试。
3. 有问题可以再联系我

**Comment by WillWang2015** [comment]
@knightliao 感谢反馈。
annotation的使用本地文件配置功能确实有问题。我使用了 https://github.com/knightliao/disconf-demos-java/tree/master/disconf-standalone-demo 进行了测试。
拉取了 https://github.com/knightliao/disconf-demos-java/tree/master/disconf-standalone-demo/conffiles 所有的文件到classpath。
运行日志如下：

```
2016-01-14 10:04:58,972 [main] INFO  com.example.disconf.demo.task.DisconfDemoTask - baobao--baifa: 5200.0
2016-01-14 10:04:58,972 [main] INFO  com.example.disconf.demo.task.DisconfDemoTask - baobao--yuerbao: 5200.0
2016-01-14 10:05:03,978 [main] INFO  com.example.disconf.demo.task.DisconfDemoTask - redis( 127.0.0.1 , 6379 ) get key : disconf_key
2016-01-14 10:05:03,978 [main] INFO  com.example.disconf.demo.task.DisconfDemoTask - redis( 127.0.0.1 , 6379 )
2016-01-14 10:05:03,990 [main] INFO  com.example.disconf.demo.task.DisconfDemoTask - code config:
2016-01-14 10:05:03,990 [main] INFO  com.example.disconf.demo.task.DisconfDemoTask - autoservice: bbd
2016-01-14 10:05:03,990 [main] INFO  com.example.disconf.demo.task.DisconfDemoTask - autoservice2: cc
2016-01-14 10:05:03,990 [main] INFO  com.example.disconf.demo.task.DisconfDemoTask - static file data: 147
2016-01-14 10:05:03,990 [main] INFO  com.example.disconf.demo.task.DisconfDemoTask - static item data: 56
```

可以看到code.properties中的属性是空。与我在自己的project中测试跟踪到的问题一致。

**Comment by knightliao** [comment]
hi, 
1. 从日志中你也可以看到，除了 code.properties有问题外，其它的配置都是正确的（他们也是采用annotation), 所以 整体上是没有问题的，code.properties 是个例，下面我们来看下code.properties

2. codeConfig的代码是

@Service
@DisconfFile(filename = "code.properties", copy2TargetDirPath = "disconf")
public class CodeConfig {

    private String codeError = "";

    @DisconfFileItem(name = "syserror.paramtype", associateField = "codeError")
    public String getCodeError() {
        return codeError;
    }

    public void setCodeError(String codeError) {
        this.codeError = codeError;
    }
}

路径是 copy2TargetDirPath = "disconf" 你把 code.properties放到 disconf目录下（resouce/disconf)下，就OK了
