### ISSUE TITLE
第一步：添加Disconf的支持 代码中方法名称 destroy  拼错

### ISSUE THREAD

**Issue by zhangyq1011** [knightliao/disconf#58]
https://github.com/knightliao/disconf/wiki/Tutorial1
第一步：添加Disconf的支持
 在applicationContext.xml里添加Bean定义：

<bean id="disconfMgrBean" class="com.baidu.disconf.client.DisconfMgrBean"
      destroy-method="destory">
    <property name="scanPackage" value="com.example.disconf.demo"/>
</bean>
<bean id="disconfMgrBean2" class="com.baidu.disconf.client.DisconfMgrBeanSecond"
      init-method="init" destroy-method="destory">
</bean>

destory  vs  destroy  
请作者修改一下吧。

**Comment by knightliao** [comment]
update , thanks~
