### ISSUE TITLE
构造一个下载器有关下载目录问题

### ISSUE THREAD

**Issue by guanlele** [knightliao/disconf#59]
打算像Tutorial 10 中介绍的实现一个配置更新下载器agent，但是所有配置都只能下载到disconf.user_define_download_dir指定的目录下么，如果我想不同的配置下载到不同的目录这个可以实现么？

**Comment by knightliao** [comment]
目前支持注解式的自定义文件路径 

看下版本 2.6.28的更新  https://github.com/knightliao/disconf/wiki/updates

基于XML的在下个版本会去支持

**Comment by guanlele** [comment]
采用注解式的方式自定义路径测试了下的确ok,但多少有些不方便修改，期待下个版本基于xml方式的自定义路径哈，3ks~~
