### ISSUE TITLE
com.baidu.disconf.web.tasks.impl.ConfigConsistencyMonitorServiceImpl 类 myTest方法打印日志不正确

### ISSUE THREAD

**Issue by zhangyq1011** [knightliao/disconf#60]
// 每3分钟执行一次自动化校验
    @Scheduled(fixedDelay = 3 * 60 * 1000)
    @Override
    public void myTest() {
        LOG.info("task schedule just testing, every 1 min");
    }

every 3 min！烦请作者修改一下。
另外有疑问此处的意图是什么？？谢谢！！！

**Comment by knightliao** [comment]
这里是当初test所致。下个版本会直接删除它。:)
