### ISSUE TITLE
SimpleRegistry 问题

### ISSUE THREAD

**Issue by cncduLee** [knightliao/disconf#64]
@Override
    public <T> T getFirstByType(Class<T> type, boolean withProxy) {
        return getFirstByType(type, withProxy);
    }

这句代码虽然没有被依赖，但是代码本身有问题，请核实。

**Comment by knightliao** [comment]
fix https://github.com/knightliao/disconf/commit/83650b3d0184b1ed2bba23ba464cf08ee4693cb7 
will release in next version

**Comment by knightliao** [comment]
thanks :)
