### ISSUE TITLE
POST /api/account/signin HTTP/1.0" 404

### ISSUE THREAD

**Issue by NestZhou** [knightliao/disconf#65]
我按照git上的步骤安装部署disconf-web, 但是在使用的过程中当我点击登陆页面的登陆，总是没有反应，查看了tomcat的日志，显示"POST /api/account/signin HTTP/1.0” 404，是不是我编译的war包有问题，本人对java不甚了解，希望能够解答（maven是直接下载后解压，设置了下PATH,其他什么都没改）

**Comment by 54ebb** [comment]
检查一下你tomcat的server.xml，是不是按下面设置的？

修改server.xml文件，在Host结点下设定Context：
<Context path="" docBase="/home/work/dsp/disconf-rd/war"></Context>

**Comment by NestZhou** [comment]
找到原因了，是WEB-INF/lib/servlet-api-2.5.jar和tomcat冲突了
唉~ 不是很了解java真是弱爆了~

**Comment by Misfit-John** [comment]
表示同样404， @NestZhou 请问你是如何处理这个问题的？删除这个jar？本地mac环境，表示一路下来都没有报错，但是请求tomcat的接口一直404。

另外，我觉得能不能加个登陆失败说明，失败了报404了，为啥连个弹窗都没有。
