### ISSUE TITLE
[Future]希望能增加非注解的回调类来处理更新配置

### ISSUE THREAD

**Issue by myoss** [knightliao/disconf#67]
wiki和demo的代码我粗略看下来，client端要做到能实时获取web端更新的配置文件，只能使用注解方式，能否实现类似taobao diamond这种回调类，自己来处理获取到的配置信息，并且不是注解的，有些场景下，我的配置文件非常个性化，而不是简单的properties属性文件的key=value形式，我希望自己来处理

```
new DefaultDiamondManager(groupID, dataID, new ManagerListenerAdapter() {
    @Override
    public void receiveConfigInfo(String configInfo) {
        System.out.println("我将在这里处理获取到的更新配置信息:" + configInfo);
    }
}
```

**Comment by 54ebb** [comment]
我也遇到相同的场景。想到一种方法，不过没测试过
（1）采用注解，只指定@DisconfFile，没有@DisconfFileItem
（2）实现IDisconfUpdate接口，完成回调
（3）把你个性化的配置“强制”转成properties文件的形式，假如能转换的话

**Comment by myoss** [comment]
1. 这样的话，还是离不开注解，我线上有很太多这种非properties的配置文件。

2. 我期望能有一种简单的回调类，将更新后的配置文件内容让我自己在代码里处理。

3. 因为注解会有很个很麻烦的事情，就是一个配置文件要对应一个java类，如果我在回调类处理的场景是同一类的，我可以定义一个，然后将配置文件的名字和版本信息，放在xml文件中配置，通过spring生成不同的bean，这样方便很多。

**Comment by knightliao** [comment]
@myoss 有道理 ，下个版本加你这个功能

**Comment by myoss** [comment]
期待这一功能，辛苦作者了 @knightliao

**Comment by 54ebb** [comment]
顶

**Comment by 54ebb** [comment]
@knightliao 想确认一下，非properties文件的回调，现在是不是不支持？只支持配置变化了，能下载到客户端？
ps：看过tutorial5/8，里面说的和上面的讨论有出入，有点混乱

**Comment by kunchong21** [comment]
我也需要非注解功能。。。。

**Comment by knightliao** [comment]
2.6.32版本中会增加 已提交至master/dev, 目前snapshot中。

**Comment by knightliao** [comment]
已经发布

**Comment by myoss** [comment]
我已经获取更新，看了文档和代码，试用下来，我是有些疑问的。

`disconf-standalone-demo`项目中的`UpdatePipelineCallback`在`windows`系统下`Paths.get(path)`会解析出错，归根结底是因为`ClassLoaderUtil`中设置的`classPath`在`windows`系统是有问题的，我在`linux`系统测试是`ok`的，希望能照顾下我们这些`windows`用户

![qq 20160327203748](https://cloud.githubusercontent.com/assets/6986459/14065449/624e332a-f45c-11e5-9695-6285a1a51e1c.png)

建议`ClassLoaderUtil`改用以下方式获取路径，或者其它方式

```java
 // 获取类加载的根路径 D:\workspaces\IntelliJ\study-java\target\classes
File f = new File(this.getClass().getResource("/").getPath());
System.out.println("获取类加载的根路径: " + f);
```

看了源码`IDisconfUpdatePipeline`接口会在更新所有配置文件的时候都会被调用，并且项目中只能有一个实现类（假设：`UpdatePipelineCallback`），而且如果项目中有注解的动态加载配置文件，也会触发这个接口，这样多次触发就要小心点了。其实也就意味着项目在使用的时候，如果有一种（比如：`txt`和`json`，随便举例）以上的配置文件，只能在`UpdatePipelineCallback`中用`if/else`这种代码来解析，接下来我就不用多说了吧。。。。


如果可以，我希望这个回调接口，就像注解接口一样，它是跟xml配置文件绑定在一起的，最大区别就是它的文件名是在xml配置文件中声明的，然后这个回调接口最好不是给路径让用户自己去读取（可能会涉及一些问题），而是直接给最新的配置文件的内容，用户应该是不用去关心`disconf-client`保存在本地的实现，因为很有可能某一天保存的策略就变化了

**Comment by knightliao** [comment]
1. Path问题回头我在windows下看看。
2. 你不想使用if else， 那就使用 注解式，那样可以更加精确。为何两种方式要同时使用？
3. “如果可以，我希望这个回调接口，就像注解接口一样，它是跟xml配置文件绑定在一起的，最大区别就是它的文件名是在xml配置文件中声明的，” 那你为何不先用注解式？注解式和XML式本来就是两种style. 当然，后续会考虑XML式实现。
4. “因为注解会有个很麻烦的事情，就是一个配置文件要对应一个java类，如果我在回调类处理的场景是同一类的，我可以定义一个，然后将配置文件的名字和版本信息，放在xml文件中配置（万一有天脑残需要变动了，需要改代码重新编译，xml的话就简单很多了），通过spring生成不同的bean，这样方便很多。” 我理解通过新发布的这个功能，你写一个通用的XML处理程序，不需要很多if else 就可以实现free的处理了。
5. 公布路径和公布文件内容 这是两种处理方式，我会考虑直接公布文件内容的方式

**Comment by knightliao** [comment]
Path的问题已经 fix http://disconf.readthedocs.io/zh_CN/latest/others/src/update.html
