### ISSUE TITLE
我打算用这个项目支持PHP，应该从哪儿入手?

### ISSUE THREAD

**Issue by lanffy** [knightliao/disconf#68]
我打算用这个项目支持PHP，应该从哪儿入手?

**Comment by knightliao** [comment]
hi, 可以利用 disconf-web 暴露出来的restful 配置获取接口来撰写相应 的client代码

**Comment by knightliao** [comment]
http://disconf.readthedocs.io/zh_CN/dev/tutorial-web/src/12-open-api-for-web-client.html
