### ISSUE TITLE
一个property文件同时用于@DisconfFile annotaion和XML配置的问题

### ISSUE THREAD

**Issue by tuuutuuu** [knightliao/disconf#70]
当配置文件中有变更时，带有@DisconfFile的配置类的Bean属性会自动更新，但通过XML配置注入的bean的属性不会自动更新。
DisconfStoreFileProcessorImpl#inject2Instance 中判断非注解的逻辑貌似不严谨。

**Comment by knightliao** [comment]
非注解模式不是采用 inject2Instance 进行注入的

**Comment by tuuutuuu** [comment]
当配置文件有变更时，不管是annotation方式还是xml配置方式，都会走到DisconfStoreFileProcessorImpl#inject2Store。
从该方法的实现来看，如果检测到配置文件以annotation方式使用了，就不考虑该配置文件是不是同时也以xml配置方式使用了，ReloadConfigurationMonitor.reload()不会被调用。

**Comment by knightliao** [comment]
嗯，不过为何两种同时使用？

**Comment by knightliao** [comment]
@tuuutuuu 这个问题我回头fix一下

**Comment by knightliao** [comment]
如果同时使用的话，会优先 使用注解的

**Comment by knightliao** [comment]
https://github.com/knightliao/disconf/wiki/updates 2.6.35 fix了
