### ISSUE TITLE
请教一个配置环境（env）的问题

### ISSUE THREAD

**Issue by dijingran** [knightliao/disconf#8]
env是定义在 disconf.properties的， 你们是怎么实现一个应用包多处部署的（测试环境用qa, 线上环境用online），是在启动脚本中处理的吗？或者是别的方式？ @knightliao

**Comment by knightliao** [comment]
https://github.com/knightliao/disconf/wiki/%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E

你看下这里的配置，通过修改disconf.properties就可以

**Comment by knightliao** [comment]
在比较成熟的系统里，一般是使用 jenkins 来定义 dev, production, qa 三个 task, 这三个task分别使用不同的disconf.properties进行打包。

**Comment by dijingran** [comment]
用jenkins 的profile 打出来的是dev, production, qa 三个不同的包，  我们这要求上线只能上测试通过的包，也就是qa这个包，所以才有这个问题。

**Comment by knightliao** [comment]
好吧，你们上线够严格，后面会考虑是否使用环境变量来解决：）
