### ISSUE TITLE
jackson的问题

### ISSUE THREAD

**Issue by kelvinfuhao** [knightliao/disconf#82]
我在配置disconf-web的过程中，发现pom.xml中无org.codehaus.jackson的lib，导致刚启动的时候有请求调用出现异常，虽然表面看起来使用无问题，但是影响到后面的集群等，希望完全去掉org.codehaus.jackson的使用，改为com.fasterxml.jackson。

**Comment by DemonAn** [comment]
我部署的过程中发现缺少这个包的话，没法正常使用。登录进去之后自动跳出来到登录页面，由于session的原因，又会自动登录进去，如此反复

**Comment by knightliao** [comment]
thanks 确实如你所说 会进行改进
http://stackoverflow.com/questions/30782706/org-codehaus-jackson-versus-com-fasterxml-jackson-core
