### ISSUE TITLE
生产的用户和权限管理

### ISSUE THREAD

**Issue by ZeeShen** [knightliao/disconf#83]
不知道真是使用起来都是怎么新增用户和管理授权的? 手动修改db么?
粗略看了一下没有这样的api? 当前用户新建的app都是不能自动授权的?
感觉在生产环境用起来很难管理

**Comment by markyao** [comment]
提供有相关API，具体界面需要自己开发

**Comment by knightliao** [comment]
已经整理出web相关API, 可以根据它自己写界面

**Comment by knightliao** [comment]
https://github.com/knightliao/disconf/wiki/Tutorial12-web%E5%BC%80%E6%94%BEAPI

**Comment by sichengLv** [comment]
**请问用户管理和权限管理实现起来复杂程度如何？**
