### ISSUE TITLE
mysql config表已经是utf8的了，为什么写的时候要调用CodeUtils.utf8ToUnicode？

### ISSUE THREAD

**Issue by 54ebb** [knightliao/disconf#85]
hi @knightliao ,
当新建一个配置项，值包含反斜杠时，主列表显示会丢失反斜杠：是因为调用相反函数unicodeToUtf8时，会丢失

**Comment by knightliao** [comment]
hi, 可以参考  http://johnny84.blog.51cto.com/2855387/950138

这是因为 JVM 运行时都是默认以 unicode来运行的，并且，所有  .properties 的读取方式均是 unicode方式。为了让 java 程序可以默认支持 配置，因此采用 unicode进行编码。

**Comment by knightliao** [comment]
![](http://ww2.sinaimg.cn/mw690/006oy5Ulgw1f4b8hbf9g4j30bf06mt92.jpg)

**Comment by knightliao** [comment]
可以使用两个 \\ 来实现

**Comment by knightliao** [comment]
\

**Comment by 54ebb** [comment]
谢谢

**Comment by shenhuaxx** [comment]
作为一个配置中心，写入配置与读取不一致这合理吗？
