### ISSUE TITLE
disconf,Spring+c3p0 出现死锁的情况。

### ISSUE THREAD

**Issue by NightAlexLy** [knightliao/disconf#86]
2016-04-20 19:13:01,273 [Timer-0] WARN  async.ThreadPoolAsynchronousRunner (ThreadPoolAsynchronousRunner.java:608)     - com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector@18b238e2 -- APPARENT DEADLOCK!!! Creating emergency threads for unassigned pending tasks!

2016-02-02 07:18:04,382 [Timer-0] WARN  async.ThreadPoolAsynchronousRunner (ThreadPoolAsynchronousRunner.java:624)     - com.mchange.v2.async.ThreadPoolAsynchronousRunner$DeadlockDetector@79cc4f50 -- APPARENT DEADLOCK!!! Complete Status:
        Managed Threads: 3
        Active Threads: 3
        Active Tasks:
                com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask@4abe695a (com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0)
                com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask@3c3077a8 (com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2)
                com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask@11ffd577 (com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#1)
        Pending Tasks:
                com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask@6e05e93
                com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask@e6fe47e
                com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask@54021399
                com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask@b57f9a4
                com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask@3cc683cd
                com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask@cf726e7
                com.mchange.v2.resourcepool.BasicResourcePool$AsyncTestIdleResourceTask@361b0e57
Pool thread stack traces:
        Thread[com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#2,5,main]
                com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:560)
        Thread[com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#0,5,main]
                com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:560)
        Thread[com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread-#1,5,main]
                com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:560)

**Comment by knightliao** [comment]
有更多的信息吗，这里看不出来死锁与disconf两者的关系
