### ISSUE TITLE
spring版本问题

### ISSUE THREAD

**Issue by zJiaJun** [knightliao/disconf#9]
项目用的spring 4.1.2版本，发现按照xml reload配置，无法reload，重启后生效。
把spring版本下降至和demo中的版本一样，3.1.2，可以reload。
在demo环境中，修改了spring版本至4.1.2，问题同样重现。
还未找出原因，能否看下是什么问题?希望能支持高版本

**Comment by knightliao** [comment]
dev 版本目前将会 支持 4.1.7 版本，请关注哦

**Comment by knightliao** [comment]
目前已经上线支持
