### ISSUE TITLE
在哪可以自定义disconf.properties路径？

### ISSUE THREAD

**Issue by gradysong** [knightliao/disconf#93]
读取配置是在：DisClientConfig.loadConfig(String filePath)
但是ConfigMgr在初始化的时候，直接传入的null，如下：
`// 导入用户配置
        DisClientConfig.getInstance().loadConfig(null);
`

我想从指定路径的文件读取，而不只classpath，还有别的方式么？烦请给于解答，万分感谢！

**Comment by knightliao** [comment]
目前只支持 classpath读取，下一个版本会支持，https://github.com/knightliao/disconf/wiki/updates 近期会发布

**Comment by gradysong** [comment]
非常期待

**Comment by knightliao** [comment]
例如使用 -Ddisconf.conf=/tmp/disconf.properties 来读取 disconf.properties 文件。默认是从classpath根目录读取此文件。

2.6.34 版本

**Comment by ChenXiaoQiang0318** [comment]
-Ddisconf.conf=/tmp/disconf.properties 怎么用？

**Comment by knightliao** [comment]
https://github.com/knightliao/disconf/wiki/%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E 可以自定义 disconf.properties文件的地址
