### ISSUE TITLE
可否在Docker Hub提供一个官方的web demo包，运行docker即可使用

### ISSUE THREAD

**Issue by Misfit-John** [knightliao/disconf#96]
disconf的部署有点长，依赖于zookeeper，mysql，nginx，tomcat，还要编译java，各种设置配置文件夹。初始化用户。能不能打一个docker的包，放在docker hub上，大家下载这个包就可以尝试这个应用了（当然这个包如果能在实际生产环境使用就更好了）。

**Comment by knightliao** [comment]
有个同学搞了一个 http://git.oschina.net/gongxusheng/docker-disconf 你看看

**Comment by Misfit-John** [comment]
哎我去，点个赞。
